// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_8u_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        start_full_n,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        start_out,
        start_write,
        data_V_data_V_dout,
        data_V_data_V_empty_n,
        data_V_data_V_read,
        res_V_data_0_V_din,
        res_V_data_0_V_full_n,
        res_V_data_0_V_write,
        res_V_data_1_V_din,
        res_V_data_1_V_full_n,
        res_V_data_1_V_write,
        res_V_data_2_V_din,
        res_V_data_2_V_full_n,
        res_V_data_2_V_write,
        res_V_data_3_V_din,
        res_V_data_3_V_full_n,
        res_V_data_3_V_write,
        res_V_data_4_V_din,
        res_V_data_4_V_full_n,
        res_V_data_4_V_write,
        res_V_data_5_V_din,
        res_V_data_5_V_full_n,
        res_V_data_5_V_write,
        res_V_data_6_V_din,
        res_V_data_6_V_full_n,
        res_V_data_6_V_write,
        res_V_data_7_V_din,
        res_V_data_7_V_full_n,
        res_V_data_7_V_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_pp0_stage0 = 3'd2;
parameter    ap_ST_fsm_state8 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
input   start_full_n;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output   start_out;
output   start_write;
input  [10:0] data_V_data_V_dout;
input   data_V_data_V_empty_n;
output   data_V_data_V_read;
output  [15:0] res_V_data_0_V_din;
input   res_V_data_0_V_full_n;
output   res_V_data_0_V_write;
output  [15:0] res_V_data_1_V_din;
input   res_V_data_1_V_full_n;
output   res_V_data_1_V_write;
output  [15:0] res_V_data_2_V_din;
input   res_V_data_2_V_full_n;
output   res_V_data_2_V_write;
output  [15:0] res_V_data_3_V_din;
input   res_V_data_3_V_full_n;
output   res_V_data_3_V_write;
output  [15:0] res_V_data_4_V_din;
input   res_V_data_4_V_full_n;
output   res_V_data_4_V_write;
output  [15:0] res_V_data_5_V_din;
input   res_V_data_5_V_full_n;
output   res_V_data_5_V_write;
output  [15:0] res_V_data_6_V_din;
input   res_V_data_6_V_full_n;
output   res_V_data_6_V_write;
output  [15:0] res_V_data_7_V_din;
input   res_V_data_7_V_full_n;
output   res_V_data_7_V_write;

reg ap_done;
reg ap_idle;
reg start_write;
reg data_V_data_V_read;
reg res_V_data_0_V_write;
reg res_V_data_1_V_write;
reg res_V_data_2_V_write;
reg res_V_data_3_V_write;
reg res_V_data_4_V_write;
reg res_V_data_5_V_write;
reg res_V_data_6_V_write;
reg res_V_data_7_V_write;

reg    real_start;
reg    start_once_reg;
reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    internal_ap_ready;
reg   [31:0] pX;
reg   [31:0] sX;
reg   [31:0] pY;
reg   [31:0] sY;
reg   [10:0] kernel_data_V_1;
reg   [10:0] kernel_data_V_4;
reg   [10:0] kernel_data_V_7;
reg   [10:0] kernel_data_V_2;
reg   [10:0] kernel_data_V_5;
reg   [10:0] kernel_data_V_8;
reg    line_buffer_Array_V_0_0_ce0;
reg    line_buffer_Array_V_0_0_we0;
wire   [10:0] line_buffer_Array_V_0_0_q0;
reg    line_buffer_Array_V_1_0_ce0;
reg    line_buffer_Array_V_1_0_we0;
wire   [10:0] line_buffer_Array_V_1_0_q0;
reg    data_V_data_V_blk_n;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
wire    ap_block_pp0_stage0;
reg   [0:0] icmp_ln79_reg_4699;
reg    res_V_data_0_V_blk_n;
reg    ap_enable_reg_pp0_iter5;
reg   [0:0] and_ln289_2_reg_4708;
reg   [0:0] and_ln289_2_reg_4708_pp0_iter4_reg;
reg    res_V_data_1_V_blk_n;
reg    res_V_data_2_V_blk_n;
reg    res_V_data_3_V_blk_n;
reg    res_V_data_4_V_blk_n;
reg    res_V_data_5_V_blk_n;
reg    res_V_data_6_V_blk_n;
reg    res_V_data_7_V_blk_n;
reg   [6:0] indvar_flatten_reg_320;
wire   [0:0] icmp_ln79_fu_2775_p2;
wire    ap_block_state2_pp0_stage0_iter0;
reg    ap_block_state3_pp0_stage0_iter1;
wire    ap_block_state4_pp0_stage0_iter2;
wire    ap_block_state5_pp0_stage0_iter3;
wire    ap_block_state6_pp0_stage0_iter4;
wire    io_acc_block_signal_op398;
reg    ap_block_state7_pp0_stage0_iter5;
reg    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln79_reg_4699_pp0_iter1_reg;
wire   [6:0] add_ln79_fu_2781_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [0:0] and_ln289_2_fu_2859_p2;
reg   [0:0] and_ln289_2_reg_4708_pp0_iter1_reg;
reg   [0:0] and_ln289_2_reg_4708_pp0_iter2_reg;
reg   [0:0] and_ln289_2_reg_4708_pp0_iter3_reg;
wire   [0:0] icmp_ln313_fu_2865_p2;
reg   [0:0] icmp_ln313_reg_4712;
wire   [0:0] icmp_ln317_fu_2915_p2;
reg   [0:0] icmp_ln317_reg_4716;
wire   [31:0] select_ln323_fu_2939_p3;
reg   [31:0] select_ln323_reg_4720;
reg  signed [10:0] tmp_data_0_V_reg_4725;
reg  signed [10:0] tmp_data_0_V_reg_4725_pp0_iter2_reg;
reg   [10:0] DataOut_V_1_reg_4734;
reg  signed [10:0] kernel_data_V_1_load_reg_4743;
reg  signed [10:0] kernel_data_V_4_load_reg_4753;
reg  signed [10:0] kernel_data_V_4_load_reg_4753_pp0_iter2_reg;
reg  signed [10:0] kernel_data_V_2_load_reg_4763;
reg  signed [10:0] kernel_data_V_5_load_reg_4772;
reg  signed [10:0] kernel_data_V_5_load_reg_4772_pp0_iter2_reg;
wire  signed [16:0] sext_ln1116_fu_2997_p1;
wire  signed [16:0] sext_ln1116_1_fu_3003_p1;
wire  signed [16:0] sext_ln1116_2_fu_3009_p1;
wire  signed [16:0] sext_ln1116_3_fu_3015_p1;
reg  signed [10:0] DataOut_V_reg_4805;
reg   [13:0] trunc_ln708_684_reg_4810;
reg   [15:0] trunc_ln708_685_reg_4815;
reg   [10:0] trunc_ln708_686_reg_4820;
reg   [15:0] trunc_ln708_687_reg_4825;
wire  signed [14:0] sext_ln1118_450_fu_3274_p1;
reg  signed [14:0] sext_ln1118_450_reg_4830;
reg  signed [14:0] sext_ln1118_450_reg_4830_pp0_iter3_reg;
reg   [15:0] trunc_ln708_691_reg_4835;
reg   [10:0] trunc_ln708_692_reg_4840;
reg   [15:0] trunc_ln708_693_reg_4845;
reg  signed [10:0] trunc_ln708_694_reg_4850;
reg   [12:0] trunc_ln708_696_reg_4856;
reg   [12:0] trunc_ln708_698_reg_4861;
reg   [15:0] trunc_ln708_703_reg_4866;
reg   [15:0] trunc_ln708_705_reg_4871;
reg   [10:0] trunc_ln708_706_reg_4876;
reg   [14:0] trunc_ln708_708_reg_4881;
reg   [15:0] trunc_ln708_709_reg_4886;
reg   [15:0] trunc_ln708_711_reg_4891;
reg  signed [10:0] trunc_ln708_713_reg_4896;
reg   [12:0] trunc_ln708_714_reg_4902;
reg   [12:0] trunc_ln708_715_reg_4907;
reg   [12:0] trunc_ln708_716_reg_4912;
reg   [10:0] trunc_ln708_717_reg_4917;
reg   [12:0] trunc_ln708_718_reg_4922;
reg  signed [12:0] trunc_ln708_719_reg_4927;
reg  signed [10:0] trunc_ln708_720_reg_4933;
reg   [11:0] trunc_ln708_721_reg_4939;
wire   [11:0] add_ln703_fu_3895_p2;
reg   [11:0] add_ln703_reg_4944;
wire   [12:0] add_ln703_1885_fu_3911_p2;
reg   [12:0] add_ln703_1885_reg_4949;
wire   [15:0] add_ln703_1888_fu_3917_p2;
reg   [15:0] add_ln703_1888_reg_4954;
reg   [15:0] add_ln703_1888_reg_4954_pp0_iter3_reg;
wire   [11:0] add_ln703_1892_fu_3923_p2;
reg   [11:0] add_ln703_1892_reg_4959;
wire   [15:0] add_ln703_1896_fu_3929_p2;
reg   [15:0] add_ln703_1896_reg_4964;
reg   [15:0] add_ln703_1896_reg_4964_pp0_iter3_reg;
wire   [10:0] add_ln703_1900_fu_3935_p2;
reg   [10:0] add_ln703_1900_reg_4969;
wire   [13:0] add_ln703_1904_fu_3941_p2;
reg   [13:0] add_ln703_1904_reg_4974;
reg   [13:0] add_ln703_1904_reg_4974_pp0_iter3_reg;
wire   [14:0] add_ln703_1910_fu_3947_p2;
reg   [14:0] add_ln703_1910_reg_4979;
wire   [11:0] add_ln703_1930_fu_3953_p2;
reg   [11:0] add_ln703_1930_reg_4984;
wire   [13:0] add_ln703_1940_fu_3969_p2;
reg   [13:0] add_ln703_1940_reg_4989;
wire  signed [15:0] sext_ln708_336_fu_4095_p1;
reg  signed [15:0] sext_ln708_336_reg_4994;
reg   [12:0] trunc_ln708_704_reg_4999;
wire   [15:0] add_ln703_1880_fu_4284_p2;
reg   [15:0] add_ln703_1880_reg_5004;
wire   [15:0] add_ln703_1881_fu_4288_p2;
reg   [15:0] add_ln703_1881_reg_5009;
wire   [14:0] add_ln703_1886_fu_4305_p2;
reg   [14:0] add_ln703_1886_reg_5014;
wire   [11:0] add_ln703_1889_fu_4311_p2;
reg   [11:0] add_ln703_1889_reg_5019;
wire   [13:0] add_ln703_1894_fu_4340_p2;
reg   [13:0] add_ln703_1894_reg_5024;
wire   [13:0] add_ln703_1897_fu_4346_p2;
reg   [13:0] add_ln703_1897_reg_5029;
wire   [13:0] add_ln703_1902_fu_4375_p2;
reg   [13:0] add_ln703_1902_reg_5034;
wire   [12:0] add_ln703_1907_fu_4391_p2;
reg   [12:0] add_ln703_1907_reg_5039;
wire   [15:0] add_ln703_1911_fu_4406_p2;
reg   [15:0] add_ln703_1911_reg_5044;
wire   [13:0] add_ln703_1912_fu_4412_p2;
reg   [13:0] add_ln703_1912_reg_5049;
wire   [14:0] add_ln703_1914_fu_4428_p2;
reg   [14:0] add_ln703_1914_reg_5054;
wire   [12:0] add_ln703_1918_fu_4434_p2;
reg   [12:0] add_ln703_1918_reg_5059;
wire   [12:0] add_ln703_1920_fu_4440_p2;
reg   [12:0] add_ln703_1920_reg_5064;
wire   [12:0] add_ln703_1922_fu_4456_p2;
reg   [12:0] add_ln703_1922_reg_5069;
wire   [15:0] add_ln703_1925_fu_4462_p2;
reg   [15:0] add_ln703_1925_reg_5074;
wire   [13:0] add_ln703_1927_fu_4478_p2;
reg   [13:0] add_ln703_1927_reg_5079;
wire   [13:0] add_ln703_1932_fu_4507_p2;
reg   [13:0] add_ln703_1932_reg_5084;
wire   [15:0] add_ln703_1934_fu_4513_p2;
reg   [15:0] add_ln703_1934_reg_5089;
wire   [15:0] add_ln703_1936_fu_4522_p2;
reg   [15:0] add_ln703_1936_reg_5094;
wire   [14:0] add_ln703_1941_fu_4540_p2;
reg   [14:0] add_ln703_1941_reg_5099;
wire   [15:0] tmp_data_4_V_fu_4556_p2;
reg   [15:0] tmp_data_4_V_reg_5104;
wire   [15:0] tmp_data_0_V_1_fu_4573_p2;
reg   [15:0] tmp_data_0_V_1_reg_5109;
wire   [15:0] tmp_data_1_V_fu_4590_p2;
reg   [15:0] tmp_data_1_V_reg_5114;
wire   [15:0] tmp_data_2_V_fu_4607_p2;
reg   [15:0] tmp_data_2_V_reg_5119;
wire   [15:0] tmp_data_3_V_fu_4625_p2;
reg   [15:0] tmp_data_3_V_reg_5124;
wire   [14:0] add_ln703_1919_fu_4638_p2;
reg   [14:0] add_ln703_1919_reg_5129;
wire   [13:0] add_ln703_1923_fu_4650_p2;
reg   [13:0] add_ln703_1923_reg_5134;
wire   [15:0] tmp_data_6_V_fu_4667_p2;
reg   [15:0] tmp_data_6_V_reg_5139;
wire   [15:0] tmp_data_7_V_fu_4680_p2;
reg   [15:0] tmp_data_7_V_reg_5144;
reg    ap_block_state1;
reg    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg   [31:0] ap_phi_mux_storemerge_i_i_phi_fu_335_p4;
reg   [31:0] ap_phi_reg_pp0_iter1_storemerge_i_i_reg_331;
wire   [31:0] ap_phi_reg_pp0_iter0_storemerge_i_i_reg_331;
wire   [31:0] add_ln326_fu_2871_p2;
wire   [31:0] select_ln328_fu_2889_p3;
wire   [31:0] add_ln321_fu_2921_p2;
reg   [31:0] ap_sig_allocacmp_sY_load;
reg   [10:0] ap_sig_allocacmp_kernel_data_V_2_load;
reg    ap_block_pp0_stage0_01001;
wire  signed [10:0] grp_fu_373_p0;
wire   [5:0] grp_fu_373_p1;
wire  signed [10:0] grp_fu_382_p0;
wire  signed [5:0] grp_fu_382_p1;
wire  signed [10:0] grp_fu_386_p0;
wire  signed [5:0] grp_fu_386_p1;
wire  signed [10:0] grp_fu_391_p0;
wire   [5:0] grp_fu_391_p1;
wire  signed [10:0] grp_fu_392_p0;
wire  signed [5:0] grp_fu_392_p1;
wire  signed [10:0] grp_fu_398_p0;
wire  signed [5:0] grp_fu_398_p1;
wire  signed [10:0] grp_fu_400_p0;
wire   [5:0] grp_fu_400_p1;
wire  signed [10:0] grp_fu_411_p0;
wire   [5:0] grp_fu_411_p1;
wire   [30:0] tmp_fu_2811_p4;
wire   [30:0] tmp_89_fu_2831_p4;
wire   [0:0] icmp_ln289_fu_2791_p2;
wire   [0:0] icmp_ln289_1_fu_2801_p2;
wire   [0:0] icmp_ln289_2_fu_2821_p2;
wire   [0:0] icmp_ln289_3_fu_2841_p2;
wire   [0:0] and_ln289_1_fu_2853_p2;
wire   [0:0] and_ln289_fu_2847_p2;
wire   [31:0] add_ln328_fu_2883_p2;
wire   [31:0] add_ln323_fu_2933_p2;
wire  signed [10:0] sext_ln1116_fu_2997_p0;
wire  signed [10:0] sext_ln1116_1_fu_3003_p0;
wire  signed [10:0] sext_ln1116_2_fu_3009_p0;
wire  signed [10:0] sext_ln1116_3_fu_3015_p0;
wire   [14:0] shl_ln_fu_3067_p3;
wire  signed [11:0] shl_ln1118_s_fu_3078_p3;
wire  signed [15:0] sext_ln1118_438_fu_3085_p1;
wire  signed [15:0] sext_ln1118_437_fu_3074_p1;
wire   [15:0] add_ln1118_fu_3093_p2;
wire   [14:0] trunc_ln_fu_3099_p4;
wire   [12:0] shl_ln1118_283_fu_3113_p3;
wire  signed [13:0] sext_ln1118_fu_3061_p1;
wire  signed [13:0] sext_ln1118_440_fu_3120_p1;
wire   [13:0] add_ln1118_74_fu_3124_p2;
wire   [12:0] trunc_ln708_s_fu_3130_p4;
wire   [13:0] shl_ln1118_284_fu_3144_p3;
wire  signed [14:0] sext_ln1118_439_fu_3089_p1;
wire  signed [14:0] sext_ln1118_442_fu_3151_p1;
wire   [14:0] sub_ln1118_fu_3155_p2;
wire   [16:0] grp_fu_391_p2;
wire  signed [11:0] sext_ln1118_436_fu_3064_p1;
wire   [11:0] sub_ln1118_565_fu_3181_p2;
wire   [16:0] grp_fu_382_p2;
wire   [12:0] shl_ln1118_285_fu_3216_p3;
wire  signed [13:0] sext_ln1118_445_fu_3210_p1;
wire  signed [13:0] sext_ln1118_447_fu_3223_p1;
wire   [13:0] add_ln1118_75_fu_3227_p2;
wire   [12:0] trunc_ln708_688_fu_3233_p4;
wire   [13:0] sub_ln1118_692_fu_3247_p2;
wire   [12:0] trunc_ln708_689_fu_3253_p4;
wire   [13:0] tmp_423_fu_3267_p3;
wire  signed [14:0] sext_ln1118_444_fu_3207_p1;
wire   [14:0] sub_ln1118_693_fu_3278_p2;
wire   [13:0] trunc_ln708_690_fu_3284_p4;
wire   [16:0] grp_fu_373_p2;
wire  signed [11:0] sext_ln1118_446_fu_3213_p1;
wire   [11:0] sub_ln1118_566_fu_3308_p2;
wire   [16:0] grp_fu_398_p2;
wire  signed [10:0] sext_ln1118_452_fu_3334_p0;
wire  signed [10:0] sext_ln1118_453_fu_3338_p0;
wire  signed [11:0] sext_ln1118_453_fu_3338_p1;
wire   [11:0] sub_ln1118_567_fu_3342_p2;
wire  signed [10:0] trunc_ln708_695_fu_3358_p1;
wire   [9:0] trunc_ln708_695_fu_3358_p4;
wire  signed [10:0] shl_ln1118_286_fu_3372_p1;
wire   [12:0] shl_ln1118_286_fu_3372_p3;
wire  signed [13:0] sext_ln1118_455_fu_3380_p1;
wire  signed [13:0] sext_ln1118_452_fu_3334_p1;
wire   [13:0] sub_ln1118_568_fu_3384_p2;
wire   [13:0] sub_ln1118_570_fu_3400_p2;
wire   [9:0] trunc_ln708_700_fu_3416_p4;
wire   [16:0] grp_fu_411_p2;
wire   [16:0] grp_fu_392_p2;
wire  signed [11:0] sext_ln1118_469_fu_3452_p1;
wire   [11:0] sub_ln1118_574_fu_3455_p2;
wire   [14:0] shl_ln1118_291_fu_3471_p3;
wire  signed [15:0] sext_ln1118_471_fu_3478_p1;
wire  signed [15:0] sext_ln1118_468_fu_3449_p1;
wire   [15:0] sub_ln1118_575_fu_3482_p2;
wire   [14:0] trunc_ln708_707_fu_3488_p4;
wire   [12:0] shl_ln1118_292_fu_3502_p3;
wire  signed [15:0] sext_ln1118_472_fu_3509_p1;
wire   [15:0] sub_ln1118_576_fu_3513_p2;
wire   [16:0] grp_fu_400_p2;
wire   [16:0] grp_fu_386_p2;
wire   [11:0] shl_ln1118_294_fu_3555_p3;
wire  signed [12:0] sext_ln1118_477_fu_3562_p1;
wire   [12:0] sub_ln1118_578_fu_3566_p2;
wire   [11:0] trunc_ln708_712_fu_3572_p4;
wire  signed [11:0] sext_ln1118_476_fu_3552_p1;
wire   [11:0] sub_ln1118_579_fu_3586_p2;
wire   [12:0] shl_ln1118_295_fu_3602_p3;
wire  signed [13:0] sext_ln1118_475_fu_3549_p1;
wire  signed [13:0] sext_ln1118_480_fu_3609_p1;
wire   [13:0] add_ln1118_76_fu_3613_p2;
wire   [13:0] sub_ln1118_580_fu_3629_p2;
wire   [13:0] sub_ln1118_581_fu_3645_p2;
wire   [13:0] sub_ln1118_582_fu_3651_p2;
wire  signed [10:0] sext_ln1118_484_fu_3667_p0;
wire  signed [10:0] sext_ln1118_485_fu_3671_p0;
wire  signed [11:0] sext_ln1118_485_fu_3671_p1;
wire   [11:0] sub_ln1118_583_fu_3675_p2;
wire  signed [10:0] tmp_424_fu_3691_p1;
wire   [12:0] tmp_424_fu_3691_p3;
wire  signed [13:0] sext_ln1118_484_fu_3667_p1;
wire  signed [13:0] sext_ln1118_488_fu_3699_p1;
wire   [13:0] sub_ln1118_695_fu_3703_p2;
wire   [13:0] add_ln1118_77_fu_3719_p2;
wire  signed [10:0] sext_ln1118_489_fu_3735_p0;
wire  signed [10:0] sext_ln1118_490_fu_3739_p0;
wire  signed [10:0] sext_ln1118_491_fu_3743_p0;
wire  signed [10:0] sext_ln1118_492_fu_3747_p0;
wire  signed [11:0] sext_ln1118_492_fu_3747_p1;
wire   [11:0] sub_ln1118_584_fu_3751_p2;
wire  signed [10:0] shl_ln1118_296_fu_3767_p1;
wire   [11:0] shl_ln1118_296_fu_3767_p3;
wire  signed [12:0] sext_ln1118_495_fu_3775_p1;
wire   [12:0] sub_ln1118_585_fu_3779_p2;
wire  signed [10:0] shl_ln1118_297_fu_3795_p1;
wire   [13:0] shl_ln1118_297_fu_3795_p3;
wire  signed [14:0] sext_ln1118_490_fu_3739_p1;
wire  signed [14:0] sext_ln1118_497_fu_3803_p1;
wire   [14:0] add_ln1118_78_fu_3807_p2;
wire   [13:0] trunc_ln708_722_fu_3813_p4;
wire  signed [10:0] tmp_425_fu_3827_p1;
wire   [12:0] tmp_425_fu_3827_p3;
wire  signed [13:0] sext_ln1118_491_fu_3743_p1;
wire  signed [13:0] sext_ln1118_498_fu_3835_p1;
wire   [13:0] sub_ln1118_696_fu_3839_p2;
wire   [12:0] trunc_ln708_723_fu_3845_p4;
wire  signed [11:0] sext_ln1118_500_fu_3859_p1;
wire   [11:0] sub_ln1118_586_fu_3862_p2;
wire   [10:0] trunc_ln708_724_fu_3868_p4;
wire   [9:0] trunc_ln708_727_fu_3882_p4;
wire   [11:0] add_ln703_1884_fu_3901_p2;
wire  signed [12:0] sext_ln1118_489_fu_3735_p1;
wire  signed [12:0] sext_ln703_637_fu_3907_p1;
wire  signed [15:0] sext_ln708_339_fu_3582_p1;
wire  signed [15:0] sext_ln708_fu_3109_p1;
wire  signed [11:0] sext_ln1118_501_fu_3878_p1;
wire  signed [15:0] sext_ln708_331_fu_3243_p1;
wire  signed [15:0] sext_ln708_337_fu_3498_p1;
wire  signed [10:0] sext_ln1118_462_fu_3425_p1;
wire  signed [10:0] sext_ln1118_454_fu_3368_p1;
wire  signed [13:0] sext_ln1118_448_fu_3263_p1;
wire  signed [13:0] sext_ln1118_441_fu_3140_p1;
wire  signed [14:0] sext_ln708_342_fu_3823_p1;
wire  signed [14:0] sext_ln1118_449_fu_3294_p1;
wire  signed [10:0] sext_ln703_fu_3891_p1;
wire   [10:0] add_ln703_1939_fu_3959_p2;
wire  signed [13:0] sext_ln1118_499_fu_3855_p1;
wire  signed [13:0] sext_ln703_670_fu_3965_p1;
wire   [11:0] shl_ln1118_287_fu_3993_p3;
wire  signed [12:0] sext_ln1118_457_fu_4000_p1;
wire   [12:0] sub_ln1118_569_fu_4004_p2;
wire  signed [11:0] trunc_ln708_697_fu_4010_p4;
wire  signed [11:0] sext_ln1118_461_fu_4034_p1;
wire   [11:0] sub_ln1118_571_fu_4037_p2;
wire   [10:0] trunc_ln708_699_fu_4043_p4;
wire   [14:0] shl_ln1118_288_fu_4057_p3;
wire   [11:0] shl_ln1118_289_fu_4068_p3;
wire  signed [15:0] sext_ln1118_463_fu_4064_p1;
wire  signed [15:0] sext_ln1118_464_fu_4075_p1;
wire   [15:0] sub_ln1118_572_fu_4079_p2;
wire   [14:0] trunc_ln708_701_fu_4085_p4;
wire   [12:0] shl_ln1118_290_fu_4099_p3;
wire  signed [13:0] sext_ln1118_465_fu_4106_p1;
wire   [13:0] sub_ln1118_573_fu_4110_p2;
wire   [12:0] trunc_ln708_702_fu_4116_p4;
wire  signed [13:0] sext_ln1118_460_fu_4031_p1;
wire   [13:0] sub_ln1118_694_fu_4130_p2;
wire   [11:0] shl_ln1118_293_fu_4152_p3;
wire  signed [12:0] sext_ln1118_473_fu_4159_p1;
wire   [12:0] sub_ln1118_577_fu_4163_p2;
wire   [11:0] trunc_ln708_710_fu_4169_p4;
wire   [12:0] shl_ln1118_298_fu_4219_p3;
wire  signed [13:0] sext_ln1118_502_fu_4226_p1;
wire   [13:0] sub_ln1118_587_fu_4230_p2;
wire   [12:0] trunc_ln708_725_fu_4236_p4;
wire   [11:0] shl_ln1118_299_fu_4250_p3;
wire  signed [12:0] sext_ln1118_504_fu_4257_p1;
wire   [12:0] sub_ln1118_588_fu_4261_p2;
wire   [11:0] trunc_ln708_726_fu_4267_p4;
wire  signed [13:0] sext_ln1118_482_fu_4192_p1;
wire  signed [13:0] sext_ln1118_456_fu_3990_p1;
wire   [13:0] add_ln703_1883_fu_4292_p2;
wire  signed [14:0] sext_ln703_636_fu_4298_p1;
wire  signed [14:0] sext_ln703_638_fu_4302_p1;
wire  signed [11:0] sext_ln708_335_fu_4053_p1;
wire  signed [11:0] sext_ln708_333_fu_3987_p1;
wire  signed [11:0] sext_ln1118_486_fu_4198_p1;
wire  signed [11:0] sext_ln1118_470_fu_4146_p1;
wire   [11:0] add_ln703_1891_fu_4317_p2;
wire  signed [12:0] sext_ln1118_494_fu_4213_p1;
wire  signed [12:0] sext_ln703_642_fu_4327_p1;
wire   [12:0] add_ln703_1893_fu_4330_p2;
wire  signed [13:0] sext_ln703_641_fu_4323_p1;
wire  signed [13:0] sext_ln703_643_fu_4336_p1;
wire  signed [13:0] sext_ln1118_503_fu_4246_p1;
wire  signed [13:0] sext_ln1118_487_fu_4201_p1;
wire  signed [12:0] sext_ln1118_496_fu_4216_p1;
wire  signed [12:0] sext_ln703_635_fu_4281_p1;
wire   [12:0] add_ln703_1899_fu_4352_p2;
wire  signed [11:0] sext_ln1118_479_fu_4186_p1;
wire  signed [11:0] sext_ln703_647_fu_4362_p1;
wire   [11:0] add_ln703_1901_fu_4365_p2;
wire  signed [13:0] sext_ln703_646_fu_4358_p1;
wire  signed [13:0] sext_ln703_648_fu_4371_p1;
wire   [11:0] add_ln703_1906_fu_4381_p2;
wire  signed [12:0] sext_ln708_343_fu_4277_p1;
wire  signed [12:0] sext_ln703_651_fu_4387_p1;
wire  signed [15:0] sext_ln708_330_fu_3975_p1;
wire  signed [15:0] sext_ln708_338_fu_4149_p1;
wire   [15:0] add_ln703_1909_fu_4397_p2;
wire  signed [15:0] sext_ln703_653_fu_4403_p1;
wire  signed [13:0] sext_ln1118_481_fu_4189_p1;
wire  signed [13:0] sext_ln1118_466_fu_4126_p1;
wire  signed [13:0] sext_ln708_332_fu_3984_p1;
wire   [13:0] add_ln703_1913_fu_4418_p2;
wire  signed [14:0] sext_ln708_341_fu_4207_p1;
wire  signed [14:0] sext_ln703_655_fu_4424_p1;
wire  signed [12:0] sext_ln1118_474_fu_4179_p1;
wire  signed [12:0] sext_ln1118_459_fu_4024_p1;
wire  signed [12:0] sext_ln1118_443_fu_3978_p1;
wire  signed [11:0] sext_ln1118_493_fu_4210_p1;
wire   [11:0] add_ln703_1921_fu_4446_p2;
wire  signed [12:0] sext_ln1118_478_fu_4183_p1;
wire  signed [12:0] sext_ln703_660_fu_4452_p1;
wire  signed [15:0] sext_ln708_340_fu_4204_p1;
wire   [12:0] add_ln703_1926_fu_4468_p2;
wire  signed [13:0] sext_ln1118_458_fu_4020_p1;
wire  signed [13:0] sext_ln703_663_fu_4474_p1;
wire  signed [11:0] sext_ln1118_451_fu_3981_p1;
wire   [11:0] add_ln703_1929_fu_4484_p2;
wire  signed [12:0] sext_ln703_666_fu_4494_p1;
wire   [12:0] add_ln703_1931_fu_4497_p2;
wire  signed [13:0] sext_ln703_665_fu_4490_p1;
wire  signed [13:0] sext_ln703_667_fu_4503_p1;
wire  signed [15:0] sext_ln708_334_fu_4028_p1;
wire   [15:0] add_ln703_1935_fu_4517_p2;
wire  signed [13:0] sext_ln1118_483_fu_4195_p1;
wire   [13:0] add_ln703_1938_fu_4527_p2;
wire  signed [14:0] sext_ln703_669_fu_4533_p1;
wire  signed [14:0] sext_ln703_671_fu_4537_p1;
wire   [15:0] add_ln703_1882_fu_4549_p2;
wire  signed [15:0] sext_ln703_639_fu_4553_p1;
wire  signed [15:0] sext_ln703_640_fu_4562_p1;
wire   [15:0] add_ln703_1890_fu_4565_p2;
wire  signed [15:0] sext_ln703_644_fu_4570_p1;
wire  signed [15:0] sext_ln703_645_fu_4579_p1;
wire   [15:0] add_ln703_1898_fu_4582_p2;
wire  signed [15:0] sext_ln703_649_fu_4587_p1;
wire  signed [15:0] sext_ln703_650_fu_4596_p1;
wire   [15:0] add_ln703_1905_fu_4599_p2;
wire  signed [15:0] sext_ln703_652_fu_4604_p1;
wire  signed [15:0] sext_ln703_654_fu_4613_p1;
wire  signed [15:0] sext_ln703_656_fu_4616_p1;
wire   [15:0] add_ln703_1915_fu_4619_p2;
wire  signed [14:0] sext_ln1118_467_fu_4546_p1;
wire   [14:0] add_ln703_1917_fu_4630_p2;
wire  signed [14:0] sext_ln703_657_fu_4635_p1;
wire  signed [13:0] sext_ln703_659_fu_4644_p1;
wire  signed [13:0] sext_ln703_661_fu_4647_p1;
wire  signed [15:0] sext_ln703_664_fu_4656_p1;
wire   [15:0] add_ln703_1928_fu_4659_p2;
wire  signed [15:0] sext_ln703_668_fu_4664_p1;
wire   [15:0] add_ln703_1937_fu_4673_p2;
wire  signed [15:0] sext_ln703_672_fu_4677_p1;
wire  signed [15:0] sext_ln703_658_fu_4686_p1;
wire  signed [15:0] sext_ln703_662_fu_4689_p1;
reg    grp_fu_373_ce;
reg    grp_fu_382_ce;
reg    grp_fu_386_ce;
reg    grp_fu_391_ce;
reg    grp_fu_392_ce;
reg    grp_fu_398_ce;
reg    grp_fu_400_ce;
reg    grp_fu_411_ce;
wire    ap_CS_fsm_state8;
reg   [2:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
reg    ap_condition_413;
reg    ap_condition_171;
reg    ap_condition_402;
reg    ap_condition_419;

// power-on initialization
initial begin
#0 start_once_reg = 1'b0;
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 pX = 32'd0;
#0 sX = 32'd0;
#0 pY = 32'd0;
#0 sY = 32'd0;
#0 kernel_data_V_1 = 11'd0;
#0 kernel_data_V_4 = 11'd0;
#0 kernel_data_V_7 = 11'd0;
#0 kernel_data_V_2 = 11'd0;
#0 kernel_data_V_5 = 11'd0;
#0 kernel_data_V_8 = 11'd0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
end

conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_8u_config3_s_line_buffbkb #(
    .DataWidth( 11 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
line_buffer_Array_V_0_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(4'd8),
    .ce0(line_buffer_Array_V_0_0_ce0),
    .we0(line_buffer_Array_V_0_0_we0),
    .d0(data_V_data_V_dout),
    .q0(line_buffer_Array_V_0_0_q0)
);

conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_8u_config3_s_line_buffbkb #(
    .DataWidth( 11 ),
    .AddressRange( 9 ),
    .AddressWidth( 4 ))
line_buffer_Array_V_1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(4'd8),
    .ce0(line_buffer_Array_V_1_0_ce0),
    .we0(line_buffer_Array_V_1_0_we0),
    .d0(DataOut_V_1_reg_4734),
    .q0(line_buffer_Array_V_1_0_q0)
);

myproject_mul_11s_6ns_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6ns_17_2_1_U4(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_373_p0),
    .din1(grp_fu_373_p1),
    .ce(grp_fu_373_ce),
    .dout(grp_fu_373_p2)
);

myproject_mul_11s_6s_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6s_17_2_1_U5(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_382_p0),
    .din1(grp_fu_382_p1),
    .ce(grp_fu_382_ce),
    .dout(grp_fu_382_p2)
);

myproject_mul_11s_6s_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6s_17_2_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_386_p0),
    .din1(grp_fu_386_p1),
    .ce(grp_fu_386_ce),
    .dout(grp_fu_386_p2)
);

myproject_mul_11s_6ns_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6ns_17_2_1_U7(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_391_p0),
    .din1(grp_fu_391_p1),
    .ce(grp_fu_391_ce),
    .dout(grp_fu_391_p2)
);

myproject_mul_11s_6s_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6s_17_2_1_U8(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_392_p0),
    .din1(grp_fu_392_p1),
    .ce(grp_fu_392_ce),
    .dout(grp_fu_392_p2)
);

myproject_mul_11s_6s_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6s_17_2_1_U9(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_398_p0),
    .din1(grp_fu_398_p1),
    .ce(grp_fu_398_ce),
    .dout(grp_fu_398_p2)
);

myproject_mul_11s_6ns_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6ns_17_2_1_U10(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_400_p0),
    .din1(grp_fu_400_p1),
    .ce(grp_fu_400_ce),
    .dout(grp_fu_400_p2)
);

myproject_mul_11s_6ns_17_2_1 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 17 ))
myproject_mul_11s_6ns_17_2_1_U11(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_411_p0),
    .din1(grp_fu_411_p1),
    .ce(grp_fu_411_ce),
    .dout(grp_fu_411_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state8)) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state2)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state2);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter5 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        start_once_reg <= 1'b0;
    end else begin
        if (((internal_ap_ready == 1'b0) & (real_start == 1'b1))) begin
            start_once_reg <= 1'b1;
        end else if ((internal_ap_ready == 1'b1)) begin
            start_once_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_171)) begin
        if ((1'b1 == ap_condition_413)) begin
            ap_phi_reg_pp0_iter1_storemerge_i_i_reg_331 <= 32'd0;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_storemerge_i_i_reg_331 <= ap_phi_reg_pp0_iter0_storemerge_i_i_reg_331;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_fu_2775_p2 == 1'd0))) begin
        indvar_flatten_reg_320 <= add_ln79_fu_2781_p2;
    end else if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_320 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_402)) begin
        if ((icmp_ln313_fu_2865_p2 == 1'd1)) begin
            pX <= 32'd0;
        end else if ((icmp_ln313_fu_2865_p2 == 1'd0)) begin
            pX <= add_ln326_fu_2871_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_419)) begin
        if ((icmp_ln317_fu_2915_p2 == 1'd1)) begin
            pY <= 32'd0;
        end else if ((icmp_ln317_fu_2915_p2 == 1'd0)) begin
            pY <= add_ln321_fu_2921_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_402)) begin
        if ((icmp_ln313_fu_2865_p2 == 1'd1)) begin
            sX <= 32'd0;
        end else if ((icmp_ln313_fu_2865_p2 == 1'd0)) begin
            sX <= select_ln328_fu_2889_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699 == 1'd0))) begin
        DataOut_V_1_reg_4734 <= line_buffer_Array_V_0_0_q0;
        kernel_data_V_1_load_reg_4743 <= kernel_data_V_1;
        kernel_data_V_2_load_reg_4763 <= ap_sig_allocacmp_kernel_data_V_2_load;
        kernel_data_V_4_load_reg_4753 <= kernel_data_V_4;
        kernel_data_V_5_load_reg_4772 <= kernel_data_V_5;
        tmp_data_0_V_reg_4725 <= data_V_data_V_dout;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699_pp0_iter1_reg == 1'd0))) begin
        DataOut_V_reg_4805 <= line_buffer_Array_V_1_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter2_reg))) begin
        add_ln703_1880_reg_5004 <= add_ln703_1880_fu_4284_p2;
        add_ln703_1881_reg_5009 <= add_ln703_1881_fu_4288_p2;
        add_ln703_1886_reg_5014 <= add_ln703_1886_fu_4305_p2;
        add_ln703_1889_reg_5019 <= add_ln703_1889_fu_4311_p2;
        add_ln703_1894_reg_5024 <= add_ln703_1894_fu_4340_p2;
        add_ln703_1897_reg_5029 <= add_ln703_1897_fu_4346_p2;
        add_ln703_1902_reg_5034 <= add_ln703_1902_fu_4375_p2;
        add_ln703_1907_reg_5039 <= add_ln703_1907_fu_4391_p2;
        add_ln703_1911_reg_5044 <= add_ln703_1911_fu_4406_p2;
        add_ln703_1912_reg_5049 <= add_ln703_1912_fu_4412_p2;
        add_ln703_1914_reg_5054 <= add_ln703_1914_fu_4428_p2;
        add_ln703_1918_reg_5059 <= add_ln703_1918_fu_4434_p2;
        add_ln703_1920_reg_5064 <= add_ln703_1920_fu_4440_p2;
        add_ln703_1922_reg_5069 <= add_ln703_1922_fu_4456_p2;
        add_ln703_1925_reg_5074 <= add_ln703_1925_fu_4462_p2;
        add_ln703_1927_reg_5079 <= add_ln703_1927_fu_4478_p2;
        add_ln703_1932_reg_5084 <= add_ln703_1932_fu_4507_p2;
        add_ln703_1934_reg_5089 <= add_ln703_1934_fu_4513_p2;
        add_ln703_1936_reg_5094 <= add_ln703_1936_fu_4522_p2;
        add_ln703_1941_reg_5099 <= add_ln703_1941_fu_4540_p2;
        sext_ln708_336_reg_4994 <= sext_ln708_336_fu_4095_p1;
        trunc_ln708_704_reg_4999 <= {{sub_ln1118_694_fu_4130_p2[13:1]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter1_reg))) begin
        add_ln703_1885_reg_4949 <= add_ln703_1885_fu_3911_p2;
        add_ln703_1888_reg_4954 <= add_ln703_1888_fu_3917_p2;
        add_ln703_1892_reg_4959 <= add_ln703_1892_fu_3923_p2;
        add_ln703_1896_reg_4964 <= add_ln703_1896_fu_3929_p2;
        add_ln703_1900_reg_4969 <= add_ln703_1900_fu_3935_p2;
        add_ln703_1904_reg_4974 <= add_ln703_1904_fu_3941_p2;
        add_ln703_1910_reg_4979 <= add_ln703_1910_fu_3947_p2;
        add_ln703_1930_reg_4984 <= add_ln703_1930_fu_3953_p2;
        add_ln703_1940_reg_4989 <= add_ln703_1940_fu_3969_p2;
        add_ln703_reg_4944 <= add_ln703_fu_3895_p2;
        sext_ln1118_450_reg_4830[14 : 3] <= sext_ln1118_450_fu_3274_p1[14 : 3];
        trunc_ln708_684_reg_4810 <= {{sub_ln1118_fu_3155_p2[14:1]}};
        trunc_ln708_685_reg_4815 <= {{grp_fu_391_p2[16:1]}};
        trunc_ln708_686_reg_4820 <= {{sub_ln1118_565_fu_3181_p2[11:1]}};
        trunc_ln708_687_reg_4825 <= {{grp_fu_382_p2[16:1]}};
        trunc_ln708_691_reg_4835 <= {{grp_fu_373_p2[16:1]}};
        trunc_ln708_692_reg_4840 <= {{sub_ln1118_566_fu_3308_p2[11:1]}};
        trunc_ln708_693_reg_4845 <= {{grp_fu_398_p2[16:1]}};
        trunc_ln708_694_reg_4850 <= {{sub_ln1118_567_fu_3342_p2[11:1]}};
        trunc_ln708_696_reg_4856 <= {{sub_ln1118_568_fu_3384_p2[13:1]}};
        trunc_ln708_698_reg_4861 <= {{sub_ln1118_570_fu_3400_p2[13:1]}};
        trunc_ln708_703_reg_4866 <= {{grp_fu_411_p2[16:1]}};
        trunc_ln708_705_reg_4871 <= {{grp_fu_392_p2[16:1]}};
        trunc_ln708_706_reg_4876 <= {{sub_ln1118_574_fu_3455_p2[11:1]}};
        trunc_ln708_708_reg_4881 <= {{sub_ln1118_576_fu_3513_p2[15:1]}};
        trunc_ln708_709_reg_4886 <= {{grp_fu_400_p2[16:1]}};
        trunc_ln708_711_reg_4891 <= {{grp_fu_386_p2[16:1]}};
        trunc_ln708_713_reg_4896 <= {{sub_ln1118_579_fu_3586_p2[11:1]}};
        trunc_ln708_714_reg_4902 <= {{add_ln1118_76_fu_3613_p2[13:1]}};
        trunc_ln708_715_reg_4907 <= {{sub_ln1118_580_fu_3629_p2[13:1]}};
        trunc_ln708_716_reg_4912 <= {{sub_ln1118_582_fu_3651_p2[13:1]}};
        trunc_ln708_717_reg_4917 <= {{sub_ln1118_583_fu_3675_p2[11:1]}};
        trunc_ln708_718_reg_4922 <= {{sub_ln1118_695_fu_3703_p2[13:1]}};
        trunc_ln708_719_reg_4927 <= {{add_ln1118_77_fu_3719_p2[13:1]}};
        trunc_ln708_720_reg_4933 <= {{sub_ln1118_584_fu_3751_p2[11:1]}};
        trunc_ln708_721_reg_4939 <= {{sub_ln1118_585_fu_3779_p2[12:1]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        add_ln703_1888_reg_4954_pp0_iter3_reg <= add_ln703_1888_reg_4954;
        add_ln703_1896_reg_4964_pp0_iter3_reg <= add_ln703_1896_reg_4964;
        add_ln703_1904_reg_4974_pp0_iter3_reg <= add_ln703_1904_reg_4974;
        and_ln289_2_reg_4708_pp0_iter2_reg <= and_ln289_2_reg_4708_pp0_iter1_reg;
        and_ln289_2_reg_4708_pp0_iter3_reg <= and_ln289_2_reg_4708_pp0_iter2_reg;
        and_ln289_2_reg_4708_pp0_iter4_reg <= and_ln289_2_reg_4708_pp0_iter3_reg;
        kernel_data_V_4_load_reg_4753_pp0_iter2_reg <= kernel_data_V_4_load_reg_4753;
        kernel_data_V_5_load_reg_4772_pp0_iter2_reg <= kernel_data_V_5_load_reg_4772;
        sext_ln1118_450_reg_4830_pp0_iter3_reg[14 : 3] <= sext_ln1118_450_reg_4830[14 : 3];
        tmp_data_0_V_reg_4725_pp0_iter2_reg <= tmp_data_0_V_reg_4725;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter3_reg))) begin
        add_ln703_1919_reg_5129 <= add_ln703_1919_fu_4638_p2;
        add_ln703_1923_reg_5134 <= add_ln703_1923_fu_4650_p2;
        tmp_data_0_V_1_reg_5109 <= tmp_data_0_V_1_fu_4573_p2;
        tmp_data_1_V_reg_5114 <= tmp_data_1_V_fu_4590_p2;
        tmp_data_2_V_reg_5119 <= tmp_data_2_V_fu_4607_p2;
        tmp_data_3_V_reg_5124 <= tmp_data_3_V_fu_4625_p2;
        tmp_data_4_V_reg_5104 <= tmp_data_4_V_fu_4556_p2;
        tmp_data_6_V_reg_5139 <= tmp_data_6_V_fu_4667_p2;
        tmp_data_7_V_reg_5144 <= tmp_data_7_V_fu_4680_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_fu_2775_p2 == 1'd0))) begin
        and_ln289_2_reg_4708 <= and_ln289_2_fu_2859_p2;
        icmp_ln313_reg_4712 <= icmp_ln313_fu_2865_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        and_ln289_2_reg_4708_pp0_iter1_reg <= and_ln289_2_reg_4708;
        icmp_ln79_reg_4699 <= icmp_ln79_fu_2775_p2;
        icmp_ln79_reg_4699_pp0_iter1_reg <= icmp_ln79_reg_4699;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln313_fu_2865_p2 == 1'd1) & (icmp_ln79_fu_2775_p2 == 1'd0))) begin
        icmp_ln317_reg_4716 <= icmp_ln317_fu_2915_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699 == 1'd0))) begin
        kernel_data_V_1 <= ap_sig_allocacmp_kernel_data_V_2_load;
        kernel_data_V_4 <= kernel_data_V_5;
        kernel_data_V_5 <= line_buffer_Array_V_0_0_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699_pp0_iter1_reg == 1'd0))) begin
        kernel_data_V_2 <= line_buffer_Array_V_1_0_q0;
        kernel_data_V_7 <= kernel_data_V_8;
        kernel_data_V_8 <= tmp_data_0_V_reg_4725;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln313_reg_4712 == 1'd1))) begin
        sY <= ap_phi_mux_storemerge_i_i_phi_fu_335_p4;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln313_fu_2865_p2 == 1'd1) & (icmp_ln317_fu_2915_p2 == 1'd0) & (icmp_ln79_fu_2775_p2 == 1'd0))) begin
        select_ln323_reg_4720 <= select_ln323_fu_2939_p3;
    end
end

always @ (*) begin
    if ((icmp_ln79_fu_2775_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((real_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln313_reg_4712 == 1'd1) & (icmp_ln317_reg_4716 == 1'd0) & (icmp_ln79_reg_4699 == 1'd0))) begin
        ap_phi_mux_storemerge_i_i_phi_fu_335_p4 = select_ln323_reg_4720;
    end else begin
        ap_phi_mux_storemerge_i_i_phi_fu_335_p4 = ap_phi_reg_pp0_iter1_storemerge_i_i_reg_331;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (icmp_ln79_reg_4699_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_kernel_data_V_2_load = line_buffer_Array_V_1_0_q0;
    end else begin
        ap_sig_allocacmp_kernel_data_V_2_load = kernel_data_V_2;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln313_reg_4712 == 1'd1) & (1'b0 == ap_block_pp0_stage0))) begin
        ap_sig_allocacmp_sY_load = ap_phi_mux_storemerge_i_i_phi_fu_335_p4;
    end else begin
        ap_sig_allocacmp_sY_load = sY;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (icmp_ln79_reg_4699 == 1'd0) & (1'b0 == ap_block_pp0_stage0))) begin
        data_V_data_V_blk_n = data_V_data_V_empty_n;
    end else begin
        data_V_data_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699 == 1'd0))) begin
        data_V_data_V_read = 1'b1;
    end else begin
        data_V_data_V_read = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_373_ce = 1'b1;
    end else begin
        grp_fu_373_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_382_ce = 1'b1;
    end else begin
        grp_fu_382_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_386_ce = 1'b1;
    end else begin
        grp_fu_386_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_391_ce = 1'b1;
    end else begin
        grp_fu_391_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_392_ce = 1'b1;
    end else begin
        grp_fu_392_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_398_ce = 1'b1;
    end else begin
        grp_fu_398_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_400_ce = 1'b1;
    end else begin
        grp_fu_400_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        grp_fu_411_ce = 1'b1;
    end else begin
        grp_fu_411_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        internal_ap_ready = 1'b1;
    end else begin
        internal_ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699 == 1'd0))) begin
        line_buffer_Array_V_0_0_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699 == 1'd0))) begin
        line_buffer_Array_V_0_0_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_0_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699_pp0_iter1_reg == 1'd0))) begin
        line_buffer_Array_V_1_0_ce0 = 1'd1;
    end else begin
        line_buffer_Array_V_1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_reg_4699_pp0_iter1_reg == 1'd0))) begin
        line_buffer_Array_V_1_0_we0 = 1'd1;
    end else begin
        line_buffer_Array_V_1_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (start_full_n == 1'b0))) begin
        real_start = 1'b0;
    end else begin
        real_start = ap_start;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_0_V_blk_n = res_V_data_0_V_full_n;
    end else begin
        res_V_data_0_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_0_V_write = 1'b1;
    end else begin
        res_V_data_0_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_1_V_blk_n = res_V_data_1_V_full_n;
    end else begin
        res_V_data_1_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_1_V_write = 1'b1;
    end else begin
        res_V_data_1_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_2_V_blk_n = res_V_data_2_V_full_n;
    end else begin
        res_V_data_2_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_2_V_write = 1'b1;
    end else begin
        res_V_data_2_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_3_V_blk_n = res_V_data_3_V_full_n;
    end else begin
        res_V_data_3_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_3_V_write = 1'b1;
    end else begin
        res_V_data_3_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_4_V_blk_n = res_V_data_4_V_full_n;
    end else begin
        res_V_data_4_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_4_V_write = 1'b1;
    end else begin
        res_V_data_4_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_5_V_blk_n = res_V_data_5_V_full_n;
    end else begin
        res_V_data_5_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_5_V_write = 1'b1;
    end else begin
        res_V_data_5_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_6_V_blk_n = res_V_data_6_V_full_n;
    end else begin
        res_V_data_6_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_6_V_write = 1'b1;
    end else begin
        res_V_data_6_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg) & (1'b0 == ap_block_pp0_stage0))) begin
        res_V_data_7_V_blk_n = res_V_data_7_V_full_n;
    end else begin
        res_V_data_7_V_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg))) begin
        res_V_data_7_V_write = 1'b1;
    end else begin
        res_V_data_7_V_write = 1'b0;
    end
end

always @ (*) begin
    if (((start_once_reg == 1'b0) & (real_start == 1'b1))) begin
        start_write = 1'b1;
    end else begin
        start_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((real_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln79_fu_2775_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)) & ~((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln79_fu_2775_p2 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b0)) | ((ap_enable_reg_pp0_iter4 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter5 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1118_74_fu_3124_p2 = ($signed(sext_ln1118_fu_3061_p1) + $signed(sext_ln1118_440_fu_3120_p1));

assign add_ln1118_75_fu_3227_p2 = ($signed(sext_ln1118_445_fu_3210_p1) + $signed(sext_ln1118_447_fu_3223_p1));

assign add_ln1118_76_fu_3613_p2 = ($signed(sext_ln1118_475_fu_3549_p1) + $signed(sext_ln1118_480_fu_3609_p1));

assign add_ln1118_77_fu_3719_p2 = ($signed(sext_ln1118_484_fu_3667_p1) + $signed(sext_ln1118_488_fu_3699_p1));

assign add_ln1118_78_fu_3807_p2 = ($signed(sext_ln1118_490_fu_3739_p1) + $signed(sext_ln1118_497_fu_3803_p1));

assign add_ln1118_fu_3093_p2 = ($signed(sext_ln1118_438_fu_3085_p1) + $signed(sext_ln1118_437_fu_3074_p1));

assign add_ln321_fu_2921_p2 = (pY + 32'd1);

assign add_ln323_fu_2933_p2 = (ap_sig_allocacmp_sY_load + 32'd1);

assign add_ln326_fu_2871_p2 = (pX + 32'd1);

assign add_ln328_fu_2883_p2 = (sX + 32'd1);

assign add_ln703_1880_fu_4284_p2 = (trunc_ln708_691_reg_4835 + trunc_ln708_685_reg_4815);

assign add_ln703_1881_fu_4288_p2 = (trunc_ln708_709_reg_4886 + trunc_ln708_703_reg_4866);

assign add_ln703_1882_fu_4549_p2 = (add_ln703_1880_reg_5004 + add_ln703_1881_reg_5009);

assign add_ln703_1883_fu_4292_p2 = ($signed(sext_ln1118_482_fu_4192_p1) + $signed(sext_ln1118_456_fu_3990_p1));

assign add_ln703_1884_fu_3901_p2 = ($signed(sext_ln1118_492_fu_3747_p1) + $signed(12'd3904));

assign add_ln703_1885_fu_3911_p2 = ($signed(sext_ln1118_489_fu_3735_p1) + $signed(sext_ln703_637_fu_3907_p1));

assign add_ln703_1886_fu_4305_p2 = ($signed(sext_ln703_636_fu_4298_p1) + $signed(sext_ln703_638_fu_4302_p1));

assign add_ln703_1888_fu_3917_p2 = ($signed(sext_ln708_339_fu_3582_p1) + $signed(sext_ln708_fu_3109_p1));

assign add_ln703_1889_fu_4311_p2 = ($signed(sext_ln708_335_fu_4053_p1) + $signed(sext_ln708_333_fu_3987_p1));

assign add_ln703_1890_fu_4565_p2 = ($signed(add_ln703_1888_reg_4954_pp0_iter3_reg) + $signed(sext_ln703_640_fu_4562_p1));

assign add_ln703_1891_fu_4317_p2 = ($signed(sext_ln1118_486_fu_4198_p1) + $signed(sext_ln1118_470_fu_4146_p1));

assign add_ln703_1892_fu_3923_p2 = ($signed(sext_ln1118_501_fu_3878_p1) + $signed(12'd3968));

assign add_ln703_1893_fu_4330_p2 = ($signed(sext_ln1118_494_fu_4213_p1) + $signed(sext_ln703_642_fu_4327_p1));

assign add_ln703_1894_fu_4340_p2 = ($signed(sext_ln703_641_fu_4323_p1) + $signed(sext_ln703_643_fu_4336_p1));

assign add_ln703_1896_fu_3929_p2 = ($signed(sext_ln708_331_fu_3243_p1) + $signed(sext_ln708_337_fu_3498_p1));

assign add_ln703_1897_fu_4346_p2 = ($signed(sext_ln1118_503_fu_4246_p1) + $signed(sext_ln1118_487_fu_4201_p1));

assign add_ln703_1898_fu_4582_p2 = ($signed(add_ln703_1896_reg_4964_pp0_iter3_reg) + $signed(sext_ln703_645_fu_4579_p1));

assign add_ln703_1899_fu_4352_p2 = ($signed(sext_ln1118_496_fu_4216_p1) + $signed(sext_ln703_635_fu_4281_p1));

assign add_ln703_1900_fu_3935_p2 = ($signed(sext_ln1118_462_fu_3425_p1) + $signed(sext_ln1118_454_fu_3368_p1));

assign add_ln703_1901_fu_4365_p2 = ($signed(sext_ln1118_479_fu_4186_p1) + $signed(sext_ln703_647_fu_4362_p1));

assign add_ln703_1902_fu_4375_p2 = ($signed(sext_ln703_646_fu_4358_p1) + $signed(sext_ln703_648_fu_4371_p1));

assign add_ln703_1904_fu_3941_p2 = ($signed(sext_ln1118_448_fu_3263_p1) + $signed(sext_ln1118_441_fu_3140_p1));

assign add_ln703_1905_fu_4599_p2 = ($signed(sext_ln708_336_reg_4994) + $signed(sext_ln703_650_fu_4596_p1));

assign add_ln703_1906_fu_4381_p2 = ($signed(sext_ln1118_486_fu_4198_p1) + $signed(12'd4032));

assign add_ln703_1907_fu_4391_p2 = ($signed(sext_ln708_343_fu_4277_p1) + $signed(sext_ln703_651_fu_4387_p1));

assign add_ln703_1909_fu_4397_p2 = ($signed(sext_ln708_330_fu_3975_p1) + $signed(sext_ln708_338_fu_4149_p1));

assign add_ln703_1910_fu_3947_p2 = ($signed(sext_ln708_342_fu_3823_p1) + $signed(sext_ln1118_449_fu_3294_p1));

assign add_ln703_1911_fu_4406_p2 = ($signed(add_ln703_1909_fu_4397_p2) + $signed(sext_ln703_653_fu_4403_p1));

assign add_ln703_1912_fu_4412_p2 = ($signed(sext_ln1118_481_fu_4189_p1) + $signed(sext_ln1118_466_fu_4126_p1));

assign add_ln703_1913_fu_4418_p2 = ($signed(sext_ln708_332_fu_3984_p1) + $signed(sext_ln1118_502_fu_4226_p1));

assign add_ln703_1914_fu_4428_p2 = ($signed(sext_ln708_341_fu_4207_p1) + $signed(sext_ln703_655_fu_4424_p1));

assign add_ln703_1915_fu_4619_p2 = ($signed(sext_ln703_654_fu_4613_p1) + $signed(sext_ln703_656_fu_4616_p1));

assign add_ln703_1917_fu_4630_p2 = ($signed(sext_ln1118_467_fu_4546_p1) + $signed(sext_ln1118_450_reg_4830_pp0_iter3_reg));

assign add_ln703_1918_fu_4434_p2 = ($signed(sext_ln1118_474_fu_4179_p1) + $signed(sext_ln1118_459_fu_4024_p1));

assign add_ln703_1919_fu_4638_p2 = ($signed(add_ln703_1917_fu_4630_p2) + $signed(sext_ln703_657_fu_4635_p1));

assign add_ln703_1920_fu_4440_p2 = ($signed(sext_ln1118_443_fu_3978_p1) + $signed(sext_ln708_343_fu_4277_p1));

assign add_ln703_1921_fu_4446_p2 = ($signed(sext_ln1118_493_fu_4210_p1) + $signed(12'd3904));

assign add_ln703_1922_fu_4456_p2 = ($signed(sext_ln1118_478_fu_4183_p1) + $signed(sext_ln703_660_fu_4452_p1));

assign add_ln703_1923_fu_4650_p2 = ($signed(sext_ln703_659_fu_4644_p1) + $signed(sext_ln703_661_fu_4647_p1));

assign add_ln703_1925_fu_4462_p2 = ($signed(sext_ln708_340_fu_4204_p1) + $signed(sext_ln708_336_fu_4095_p1));

assign add_ln703_1926_fu_4468_p2 = ($signed(sext_ln1118_443_fu_3978_p1) + $signed(sext_ln1118_496_fu_4216_p1));

assign add_ln703_1927_fu_4478_p2 = ($signed(sext_ln1118_458_fu_4020_p1) + $signed(sext_ln703_663_fu_4474_p1));

assign add_ln703_1928_fu_4659_p2 = ($signed(add_ln703_1925_reg_5074) + $signed(sext_ln703_664_fu_4656_p1));

assign add_ln703_1929_fu_4484_p2 = ($signed(sext_ln1118_470_fu_4146_p1) + $signed(sext_ln1118_451_fu_3981_p1));

assign add_ln703_1930_fu_3953_p2 = ($signed(sext_ln1118_501_fu_3878_p1) + $signed(12'd3840));

assign add_ln703_1931_fu_4497_p2 = ($signed(sext_ln1118_478_fu_4183_p1) + $signed(sext_ln703_666_fu_4494_p1));

assign add_ln703_1932_fu_4507_p2 = ($signed(sext_ln703_665_fu_4490_p1) + $signed(sext_ln703_667_fu_4503_p1));

assign add_ln703_1934_fu_4513_p2 = (trunc_ln708_693_reg_4845 + trunc_ln708_687_reg_4825);

assign add_ln703_1935_fu_4517_p2 = ($signed(sext_ln708_334_fu_4028_p1) + $signed(trunc_ln708_711_reg_4891));

assign add_ln703_1936_fu_4522_p2 = (trunc_ln708_705_reg_4871 + add_ln703_1935_fu_4517_p2);

assign add_ln703_1937_fu_4673_p2 = (add_ln703_1934_reg_5089 + add_ln703_1936_reg_5094);

assign add_ln703_1938_fu_4527_p2 = ($signed(sext_ln1118_487_fu_4201_p1) + $signed(sext_ln1118_483_fu_4195_p1));

assign add_ln703_1939_fu_3959_p2 = ($signed(sext_ln703_fu_3891_p1) + $signed(11'd192));

assign add_ln703_1940_fu_3969_p2 = ($signed(sext_ln1118_499_fu_3855_p1) + $signed(sext_ln703_670_fu_3965_p1));

assign add_ln703_1941_fu_4540_p2 = ($signed(sext_ln703_669_fu_4533_p1) + $signed(sext_ln703_671_fu_4537_p1));

assign add_ln703_fu_3895_p2 = ($signed(sext_ln1118_436_fu_3064_p1) + $signed(12'd3840));

assign add_ln79_fu_2781_p2 = (indvar_flatten_reg_320 + 7'd1);

assign and_ln289_1_fu_2853_p2 = (icmp_ln289_3_fu_2841_p2 & icmp_ln289_2_fu_2821_p2);

assign and_ln289_2_fu_2859_p2 = (and_ln289_fu_2847_p2 & and_ln289_1_fu_2853_p2);

assign and_ln289_fu_2847_p2 = (icmp_ln289_fu_2791_p2 & icmp_ln289_1_fu_2801_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd2];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = (((io_acc_block_signal_op398 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg)) | ((data_V_data_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln79_reg_4699 == 1'd0)));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = (((io_acc_block_signal_op398 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg)) | ((data_V_data_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln79_reg_4699 == 1'd0)));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = (((io_acc_block_signal_op398 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b1) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg)) | ((data_V_data_V_empty_n == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (icmp_ln79_reg_4699 == 1'd0)));
end

always @ (*) begin
    ap_block_state1 = ((real_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((data_V_data_V_empty_n == 1'b0) & (icmp_ln79_reg_4699 == 1'd0));
end

assign ap_block_state4_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state7_pp0_stage0_iter5 = ((io_acc_block_signal_op398 == 1'b0) & (1'd1 == and_ln289_2_reg_4708_pp0_iter4_reg));
end

always @ (*) begin
    ap_condition_171 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001));
end

always @ (*) begin
    ap_condition_402 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln79_fu_2775_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_413 = ((icmp_ln317_fu_2915_p2 == 1'd1) & (icmp_ln313_fu_2865_p2 == 1'd1) & (icmp_ln79_fu_2775_p2 == 1'd0));
end

always @ (*) begin
    ap_condition_419 = ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln313_fu_2865_p2 == 1'd1) & (icmp_ln79_fu_2775_p2 == 1'd0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_phi_reg_pp0_iter0_storemerge_i_i_reg_331 = 'bx;

assign ap_ready = internal_ap_ready;

assign grp_fu_373_p0 = sext_ln1116_1_fu_3003_p1;

assign grp_fu_373_p1 = 17'd23;

assign grp_fu_382_p0 = sext_ln1116_fu_2997_p1;

assign grp_fu_382_p1 = 17'd131046;

assign grp_fu_386_p0 = sext_ln1116_3_fu_3015_p1;

assign grp_fu_386_p1 = 17'd131043;

assign grp_fu_391_p0 = sext_ln1116_fu_2997_p1;

assign grp_fu_391_p1 = 17'd21;

assign grp_fu_392_p0 = sext_ln1116_2_fu_3009_p1;

assign grp_fu_392_p1 = 17'd131046;

assign grp_fu_398_p0 = sext_ln1116_1_fu_3003_p1;

assign grp_fu_398_p1 = 17'd131045;

assign grp_fu_400_p0 = sext_ln1116_3_fu_3015_p1;

assign grp_fu_400_p1 = 17'd23;

assign grp_fu_411_p0 = sext_ln1116_2_fu_3009_p1;

assign grp_fu_411_p1 = 17'd21;

assign icmp_ln289_1_fu_2801_p2 = ((ap_sig_allocacmp_sY_load == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln289_2_fu_2821_p2 = (($signed(tmp_fu_2811_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_3_fu_2841_p2 = (($signed(tmp_89_fu_2831_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln289_fu_2791_p2 = ((sX == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln313_fu_2865_p2 = ((pX == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln317_fu_2915_p2 = ((pY == 32'd8) ? 1'b1 : 1'b0);

assign icmp_ln79_fu_2775_p2 = ((indvar_flatten_reg_320 == 7'd81) ? 1'b1 : 1'b0);

assign io_acc_block_signal_op398 = (res_V_data_7_V_full_n & res_V_data_6_V_full_n & res_V_data_5_V_full_n & res_V_data_4_V_full_n & res_V_data_3_V_full_n & res_V_data_2_V_full_n & res_V_data_1_V_full_n & res_V_data_0_V_full_n);

assign res_V_data_0_V_din = tmp_data_0_V_1_reg_5109;

assign res_V_data_1_V_din = tmp_data_1_V_reg_5114;

assign res_V_data_2_V_din = tmp_data_2_V_reg_5119;

assign res_V_data_3_V_din = tmp_data_3_V_reg_5124;

assign res_V_data_4_V_din = tmp_data_4_V_reg_5104;

assign res_V_data_5_V_din = ($signed(sext_ln703_658_fu_4686_p1) + $signed(sext_ln703_662_fu_4689_p1));

assign res_V_data_6_V_din = tmp_data_6_V_reg_5139;

assign res_V_data_7_V_din = tmp_data_7_V_reg_5144;

assign select_ln323_fu_2939_p3 = ((icmp_ln289_1_fu_2801_p2[0:0] === 1'b1) ? 32'd1 : add_ln323_fu_2933_p2);

assign select_ln328_fu_2889_p3 = ((icmp_ln289_fu_2791_p2[0:0] === 1'b1) ? 32'd1 : add_ln328_fu_2883_p2);

assign sext_ln1116_1_fu_3003_p0 = ap_sig_allocacmp_kernel_data_V_2_load;

assign sext_ln1116_1_fu_3003_p1 = sext_ln1116_1_fu_3003_p0;

assign sext_ln1116_2_fu_3009_p0 = kernel_data_V_4;

assign sext_ln1116_2_fu_3009_p1 = sext_ln1116_2_fu_3009_p0;

assign sext_ln1116_3_fu_3015_p0 = kernel_data_V_5;

assign sext_ln1116_3_fu_3015_p1 = sext_ln1116_3_fu_3015_p0;

assign sext_ln1116_fu_2997_p0 = kernel_data_V_1;

assign sext_ln1116_fu_2997_p1 = sext_ln1116_fu_2997_p0;

assign sext_ln1118_436_fu_3064_p1 = kernel_data_V_1_load_reg_4743;

assign sext_ln1118_437_fu_3074_p1 = $signed(shl_ln_fu_3067_p3);

assign sext_ln1118_438_fu_3085_p1 = shl_ln1118_s_fu_3078_p3;

assign sext_ln1118_439_fu_3089_p1 = shl_ln1118_s_fu_3078_p3;

assign sext_ln1118_440_fu_3120_p1 = $signed(shl_ln1118_283_fu_3113_p3);

assign sext_ln1118_441_fu_3140_p1 = $signed(trunc_ln708_s_fu_3130_p4);

assign sext_ln1118_442_fu_3151_p1 = $signed(shl_ln1118_284_fu_3144_p3);

assign sext_ln1118_443_fu_3978_p1 = $signed(trunc_ln708_686_reg_4820);

assign sext_ln1118_444_fu_3207_p1 = kernel_data_V_2_load_reg_4763;

assign sext_ln1118_445_fu_3210_p1 = kernel_data_V_2_load_reg_4763;

assign sext_ln1118_446_fu_3213_p1 = kernel_data_V_2_load_reg_4763;

assign sext_ln1118_447_fu_3223_p1 = $signed(shl_ln1118_285_fu_3216_p3);

assign sext_ln1118_448_fu_3263_p1 = $signed(trunc_ln708_689_fu_3253_p4);

assign sext_ln1118_449_fu_3294_p1 = $signed(trunc_ln708_690_fu_3284_p4);

assign sext_ln1118_450_fu_3274_p1 = $signed(tmp_423_fu_3267_p3);

assign sext_ln1118_451_fu_3981_p1 = $signed(trunc_ln708_692_reg_4840);

assign sext_ln1118_452_fu_3334_p0 = line_buffer_Array_V_1_0_q0;

assign sext_ln1118_452_fu_3334_p1 = sext_ln1118_452_fu_3334_p0;

assign sext_ln1118_453_fu_3338_p0 = line_buffer_Array_V_1_0_q0;

assign sext_ln1118_453_fu_3338_p1 = sext_ln1118_453_fu_3338_p0;

assign sext_ln1118_454_fu_3368_p1 = $signed(trunc_ln708_695_fu_3358_p4);

assign sext_ln1118_455_fu_3380_p1 = $signed(shl_ln1118_286_fu_3372_p3);

assign sext_ln1118_456_fu_3990_p1 = $signed(trunc_ln708_696_reg_4856);

assign sext_ln1118_457_fu_4000_p1 = $signed(shl_ln1118_287_fu_3993_p3);

assign sext_ln1118_458_fu_4020_p1 = trunc_ln708_697_fu_4010_p4;

assign sext_ln1118_459_fu_4024_p1 = trunc_ln708_697_fu_4010_p4;

assign sext_ln1118_460_fu_4031_p1 = kernel_data_V_4_load_reg_4753_pp0_iter2_reg;

assign sext_ln1118_461_fu_4034_p1 = kernel_data_V_4_load_reg_4753_pp0_iter2_reg;

assign sext_ln1118_462_fu_3425_p1 = $signed(trunc_ln708_700_fu_3416_p4);

assign sext_ln1118_463_fu_4064_p1 = $signed(shl_ln1118_288_fu_4057_p3);

assign sext_ln1118_464_fu_4075_p1 = $signed(shl_ln1118_289_fu_4068_p3);

assign sext_ln1118_465_fu_4106_p1 = $signed(shl_ln1118_290_fu_4099_p3);

assign sext_ln1118_466_fu_4126_p1 = $signed(trunc_ln708_702_fu_4116_p4);

assign sext_ln1118_467_fu_4546_p1 = $signed(trunc_ln708_704_reg_4999);

assign sext_ln1118_468_fu_3449_p1 = kernel_data_V_5_load_reg_4772;

assign sext_ln1118_469_fu_3452_p1 = kernel_data_V_5_load_reg_4772;

assign sext_ln1118_470_fu_4146_p1 = $signed(trunc_ln708_706_reg_4876);

assign sext_ln1118_471_fu_3478_p1 = $signed(shl_ln1118_291_fu_3471_p3);

assign sext_ln1118_472_fu_3509_p1 = $signed(shl_ln1118_292_fu_3502_p3);

assign sext_ln1118_473_fu_4159_p1 = $signed(shl_ln1118_293_fu_4152_p3);

assign sext_ln1118_474_fu_4179_p1 = $signed(trunc_ln708_710_fu_4169_p4);

assign sext_ln1118_475_fu_3549_p1 = $signed(DataOut_V_1_reg_4734);

assign sext_ln1118_476_fu_3552_p1 = $signed(DataOut_V_1_reg_4734);

assign sext_ln1118_477_fu_3562_p1 = $signed(shl_ln1118_294_fu_3555_p3);

assign sext_ln1118_478_fu_4183_p1 = trunc_ln708_713_reg_4896;

assign sext_ln1118_479_fu_4186_p1 = trunc_ln708_713_reg_4896;

assign sext_ln1118_480_fu_3609_p1 = $signed(shl_ln1118_295_fu_3602_p3);

assign sext_ln1118_481_fu_4189_p1 = $signed(trunc_ln708_714_reg_4902);

assign sext_ln1118_482_fu_4192_p1 = $signed(trunc_ln708_715_reg_4907);

assign sext_ln1118_483_fu_4195_p1 = $signed(trunc_ln708_716_reg_4912);

assign sext_ln1118_484_fu_3667_p0 = kernel_data_V_7;

assign sext_ln1118_484_fu_3667_p1 = sext_ln1118_484_fu_3667_p0;

assign sext_ln1118_485_fu_3671_p0 = kernel_data_V_7;

assign sext_ln1118_485_fu_3671_p1 = sext_ln1118_485_fu_3671_p0;

assign sext_ln1118_486_fu_4198_p1 = $signed(trunc_ln708_717_reg_4917);

assign sext_ln1118_487_fu_4201_p1 = $signed(trunc_ln708_718_reg_4922);

assign sext_ln1118_488_fu_3699_p1 = $signed(tmp_424_fu_3691_p3);

assign sext_ln1118_489_fu_3735_p0 = kernel_data_V_7;

assign sext_ln1118_489_fu_3735_p1 = sext_ln1118_489_fu_3735_p0;

assign sext_ln1118_490_fu_3739_p0 = kernel_data_V_8;

assign sext_ln1118_490_fu_3739_p1 = sext_ln1118_490_fu_3739_p0;

assign sext_ln1118_491_fu_3743_p0 = kernel_data_V_8;

assign sext_ln1118_491_fu_3743_p1 = sext_ln1118_491_fu_3743_p0;

assign sext_ln1118_492_fu_3747_p0 = kernel_data_V_8;

assign sext_ln1118_492_fu_3747_p1 = sext_ln1118_492_fu_3747_p0;

assign sext_ln1118_493_fu_4210_p1 = trunc_ln708_720_reg_4933;

assign sext_ln1118_494_fu_4213_p1 = trunc_ln708_720_reg_4933;

assign sext_ln1118_495_fu_3775_p1 = $signed(shl_ln1118_296_fu_3767_p3);

assign sext_ln1118_496_fu_4216_p1 = $signed(trunc_ln708_721_reg_4939);

assign sext_ln1118_497_fu_3803_p1 = $signed(shl_ln1118_297_fu_3795_p3);

assign sext_ln1118_498_fu_3835_p1 = $signed(tmp_425_fu_3827_p3);

assign sext_ln1118_499_fu_3855_p1 = $signed(trunc_ln708_723_fu_3845_p4);

assign sext_ln1118_500_fu_3859_p1 = tmp_data_0_V_reg_4725;

assign sext_ln1118_501_fu_3878_p1 = $signed(trunc_ln708_724_fu_3868_p4);

assign sext_ln1118_502_fu_4226_p1 = $signed(shl_ln1118_298_fu_4219_p3);

assign sext_ln1118_503_fu_4246_p1 = $signed(trunc_ln708_725_fu_4236_p4);

assign sext_ln1118_504_fu_4257_p1 = $signed(shl_ln1118_299_fu_4250_p3);

assign sext_ln1118_fu_3061_p1 = kernel_data_V_1_load_reg_4743;

assign sext_ln703_635_fu_4281_p1 = $signed(add_ln703_reg_4944);

assign sext_ln703_636_fu_4298_p1 = $signed(add_ln703_1883_fu_4292_p2);

assign sext_ln703_637_fu_3907_p1 = $signed(add_ln703_1884_fu_3901_p2);

assign sext_ln703_638_fu_4302_p1 = $signed(add_ln703_1885_reg_4949);

assign sext_ln703_639_fu_4553_p1 = $signed(add_ln703_1886_reg_5014);

assign sext_ln703_640_fu_4562_p1 = $signed(add_ln703_1889_reg_5019);

assign sext_ln703_641_fu_4323_p1 = $signed(add_ln703_1891_fu_4317_p2);

assign sext_ln703_642_fu_4327_p1 = $signed(add_ln703_1892_reg_4959);

assign sext_ln703_643_fu_4336_p1 = $signed(add_ln703_1893_fu_4330_p2);

assign sext_ln703_644_fu_4570_p1 = $signed(add_ln703_1894_reg_5024);

assign sext_ln703_645_fu_4579_p1 = $signed(add_ln703_1897_reg_5029);

assign sext_ln703_646_fu_4358_p1 = $signed(add_ln703_1899_fu_4352_p2);

assign sext_ln703_647_fu_4362_p1 = $signed(add_ln703_1900_reg_4969);

assign sext_ln703_648_fu_4371_p1 = $signed(add_ln703_1901_fu_4365_p2);

assign sext_ln703_649_fu_4587_p1 = $signed(add_ln703_1902_reg_5034);

assign sext_ln703_650_fu_4596_p1 = $signed(add_ln703_1904_reg_4974_pp0_iter3_reg);

assign sext_ln703_651_fu_4387_p1 = $signed(add_ln703_1906_fu_4381_p2);

assign sext_ln703_652_fu_4604_p1 = $signed(add_ln703_1907_reg_5039);

assign sext_ln703_653_fu_4403_p1 = $signed(add_ln703_1910_reg_4979);

assign sext_ln703_654_fu_4613_p1 = $signed(add_ln703_1912_reg_5049);

assign sext_ln703_655_fu_4424_p1 = $signed(add_ln703_1913_fu_4418_p2);

assign sext_ln703_656_fu_4616_p1 = $signed(add_ln703_1914_reg_5054);

assign sext_ln703_657_fu_4635_p1 = $signed(add_ln703_1918_reg_5059);

assign sext_ln703_658_fu_4686_p1 = $signed(add_ln703_1919_reg_5129);

assign sext_ln703_659_fu_4644_p1 = $signed(add_ln703_1920_reg_5064);

assign sext_ln703_660_fu_4452_p1 = $signed(add_ln703_1921_fu_4446_p2);

assign sext_ln703_661_fu_4647_p1 = $signed(add_ln703_1922_reg_5069);

assign sext_ln703_662_fu_4689_p1 = $signed(add_ln703_1923_reg_5134);

assign sext_ln703_663_fu_4474_p1 = $signed(add_ln703_1926_fu_4468_p2);

assign sext_ln703_664_fu_4656_p1 = $signed(add_ln703_1927_reg_5079);

assign sext_ln703_665_fu_4490_p1 = $signed(add_ln703_1929_fu_4484_p2);

assign sext_ln703_666_fu_4494_p1 = $signed(add_ln703_1930_reg_4984);

assign sext_ln703_667_fu_4503_p1 = $signed(add_ln703_1931_fu_4497_p2);

assign sext_ln703_668_fu_4664_p1 = $signed(add_ln703_1932_reg_5084);

assign sext_ln703_669_fu_4533_p1 = $signed(add_ln703_1938_fu_4527_p2);

assign sext_ln703_670_fu_3965_p1 = $signed(add_ln703_1939_fu_3959_p2);

assign sext_ln703_671_fu_4537_p1 = $signed(add_ln703_1940_reg_4989);

assign sext_ln703_672_fu_4677_p1 = $signed(add_ln703_1941_reg_5099);

assign sext_ln703_fu_3891_p1 = $signed(trunc_ln708_727_fu_3882_p4);

assign sext_ln708_330_fu_3975_p1 = $signed(trunc_ln708_684_reg_4810);

assign sext_ln708_331_fu_3243_p1 = $signed(trunc_ln708_688_fu_3233_p4);

assign sext_ln708_332_fu_3984_p1 = trunc_ln708_694_reg_4850;

assign sext_ln708_333_fu_3987_p1 = trunc_ln708_694_reg_4850;

assign sext_ln708_334_fu_4028_p1 = $signed(trunc_ln708_698_reg_4861);

assign sext_ln708_335_fu_4053_p1 = $signed(trunc_ln708_699_fu_4043_p4);

assign sext_ln708_336_fu_4095_p1 = $signed(trunc_ln708_701_fu_4085_p4);

assign sext_ln708_337_fu_3498_p1 = $signed(trunc_ln708_707_fu_3488_p4);

assign sext_ln708_338_fu_4149_p1 = $signed(trunc_ln708_708_reg_4881);

assign sext_ln708_339_fu_3582_p1 = $signed(trunc_ln708_712_fu_3572_p4);

assign sext_ln708_340_fu_4204_p1 = trunc_ln708_719_reg_4927;

assign sext_ln708_341_fu_4207_p1 = trunc_ln708_719_reg_4927;

assign sext_ln708_342_fu_3823_p1 = $signed(trunc_ln708_722_fu_3813_p4);

assign sext_ln708_343_fu_4277_p1 = $signed(trunc_ln708_726_fu_4267_p4);

assign sext_ln708_fu_3109_p1 = $signed(trunc_ln_fu_3099_p4);

assign shl_ln1118_283_fu_3113_p3 = {{kernel_data_V_1_load_reg_4743}, {2'd0}};

assign shl_ln1118_284_fu_3144_p3 = {{kernel_data_V_1_load_reg_4743}, {3'd0}};

assign shl_ln1118_285_fu_3216_p3 = {{kernel_data_V_2_load_reg_4763}, {2'd0}};

assign shl_ln1118_286_fu_3372_p1 = line_buffer_Array_V_1_0_q0;

assign shl_ln1118_286_fu_3372_p3 = {{shl_ln1118_286_fu_3372_p1}, {2'd0}};

assign shl_ln1118_287_fu_3993_p3 = {{DataOut_V_reg_4805}, {1'd0}};

assign shl_ln1118_288_fu_4057_p3 = {{kernel_data_V_4_load_reg_4753_pp0_iter2_reg}, {4'd0}};

assign shl_ln1118_289_fu_4068_p3 = {{kernel_data_V_4_load_reg_4753_pp0_iter2_reg}, {1'd0}};

assign shl_ln1118_290_fu_4099_p3 = {{kernel_data_V_4_load_reg_4753_pp0_iter2_reg}, {2'd0}};

assign shl_ln1118_291_fu_3471_p3 = {{kernel_data_V_5_load_reg_4772}, {4'd0}};

assign shl_ln1118_292_fu_3502_p3 = {{kernel_data_V_5_load_reg_4772}, {2'd0}};

assign shl_ln1118_293_fu_4152_p3 = {{kernel_data_V_5_load_reg_4772_pp0_iter2_reg}, {1'd0}};

assign shl_ln1118_294_fu_3555_p3 = {{DataOut_V_1_reg_4734}, {1'd0}};

assign shl_ln1118_295_fu_3602_p3 = {{DataOut_V_1_reg_4734}, {2'd0}};

assign shl_ln1118_296_fu_3767_p1 = kernel_data_V_8;

assign shl_ln1118_296_fu_3767_p3 = {{shl_ln1118_296_fu_3767_p1}, {1'd0}};

assign shl_ln1118_297_fu_3795_p1 = kernel_data_V_8;

assign shl_ln1118_297_fu_3795_p3 = {{shl_ln1118_297_fu_3795_p1}, {3'd0}};

assign shl_ln1118_298_fu_4219_p3 = {{tmp_data_0_V_reg_4725_pp0_iter2_reg}, {2'd0}};

assign shl_ln1118_299_fu_4250_p3 = {{tmp_data_0_V_reg_4725_pp0_iter2_reg}, {1'd0}};

assign shl_ln1118_s_fu_3078_p3 = {{kernel_data_V_1_load_reg_4743}, {1'd0}};

assign shl_ln_fu_3067_p3 = {{kernel_data_V_1_load_reg_4743}, {4'd0}};

assign start_out = real_start;

assign sub_ln1118_565_fu_3181_p2 = ($signed(12'd0) - $signed(sext_ln1118_436_fu_3064_p1));

assign sub_ln1118_566_fu_3308_p2 = ($signed(12'd0) - $signed(sext_ln1118_446_fu_3213_p1));

assign sub_ln1118_567_fu_3342_p2 = ($signed(12'd0) - $signed(sext_ln1118_453_fu_3338_p1));

assign sub_ln1118_568_fu_3384_p2 = ($signed(sext_ln1118_455_fu_3380_p1) - $signed(sext_ln1118_452_fu_3334_p1));

assign sub_ln1118_569_fu_4004_p2 = ($signed(13'd0) - $signed(sext_ln1118_457_fu_4000_p1));

assign sub_ln1118_570_fu_3400_p2 = ($signed(14'd0) - $signed(sext_ln1118_455_fu_3380_p1));

assign sub_ln1118_571_fu_4037_p2 = ($signed(12'd0) - $signed(sext_ln1118_461_fu_4034_p1));

assign sub_ln1118_572_fu_4079_p2 = ($signed(sext_ln1118_463_fu_4064_p1) - $signed(sext_ln1118_464_fu_4075_p1));

assign sub_ln1118_573_fu_4110_p2 = ($signed(14'd0) - $signed(sext_ln1118_465_fu_4106_p1));

assign sub_ln1118_574_fu_3455_p2 = ($signed(12'd0) - $signed(sext_ln1118_469_fu_3452_p1));

assign sub_ln1118_575_fu_3482_p2 = ($signed(sext_ln1118_471_fu_3478_p1) - $signed(sext_ln1118_468_fu_3449_p1));

assign sub_ln1118_576_fu_3513_p2 = ($signed(sext_ln1118_471_fu_3478_p1) - $signed(sext_ln1118_472_fu_3509_p1));

assign sub_ln1118_577_fu_4163_p2 = ($signed(13'd0) - $signed(sext_ln1118_473_fu_4159_p1));

assign sub_ln1118_578_fu_3566_p2 = ($signed(13'd0) - $signed(sext_ln1118_477_fu_3562_p1));

assign sub_ln1118_579_fu_3586_p2 = ($signed(12'd0) - $signed(sext_ln1118_476_fu_3552_p1));

assign sub_ln1118_580_fu_3629_p2 = ($signed(sext_ln1118_480_fu_3609_p1) - $signed(sext_ln1118_475_fu_3549_p1));

assign sub_ln1118_581_fu_3645_p2 = ($signed(14'd0) - $signed(sext_ln1118_480_fu_3609_p1));

assign sub_ln1118_582_fu_3651_p2 = ($signed(sub_ln1118_581_fu_3645_p2) - $signed(sext_ln1118_475_fu_3549_p1));

assign sub_ln1118_583_fu_3675_p2 = ($signed(12'd0) - $signed(sext_ln1118_485_fu_3671_p1));

assign sub_ln1118_584_fu_3751_p2 = ($signed(12'd0) - $signed(sext_ln1118_492_fu_3747_p1));

assign sub_ln1118_585_fu_3779_p2 = ($signed(13'd0) - $signed(sext_ln1118_495_fu_3775_p1));

assign sub_ln1118_586_fu_3862_p2 = ($signed(12'd0) - $signed(sext_ln1118_500_fu_3859_p1));

assign sub_ln1118_587_fu_4230_p2 = ($signed(14'd0) - $signed(sext_ln1118_502_fu_4226_p1));

assign sub_ln1118_588_fu_4261_p2 = ($signed(13'd0) - $signed(sext_ln1118_504_fu_4257_p1));

assign sub_ln1118_692_fu_3247_p2 = ($signed(sext_ln1118_445_fu_3210_p1) - $signed(sext_ln1118_447_fu_3223_p1));

assign sub_ln1118_693_fu_3278_p2 = ($signed(sext_ln1118_444_fu_3207_p1) - $signed(sext_ln1118_450_fu_3274_p1));

assign sub_ln1118_694_fu_4130_p2 = ($signed(sext_ln1118_460_fu_4031_p1) - $signed(sext_ln1118_465_fu_4106_p1));

assign sub_ln1118_695_fu_3703_p2 = ($signed(sext_ln1118_484_fu_3667_p1) - $signed(sext_ln1118_488_fu_3699_p1));

assign sub_ln1118_696_fu_3839_p2 = ($signed(sext_ln1118_491_fu_3743_p1) - $signed(sext_ln1118_498_fu_3835_p1));

assign sub_ln1118_fu_3155_p2 = ($signed(sext_ln1118_439_fu_3089_p1) - $signed(sext_ln1118_442_fu_3151_p1));

assign tmp_423_fu_3267_p3 = {{kernel_data_V_2_load_reg_4763}, {3'd0}};

assign tmp_424_fu_3691_p1 = kernel_data_V_7;

assign tmp_424_fu_3691_p3 = {{tmp_424_fu_3691_p1}, {2'd0}};

assign tmp_425_fu_3827_p1 = kernel_data_V_8;

assign tmp_425_fu_3827_p3 = {{tmp_425_fu_3827_p1}, {2'd0}};

assign tmp_89_fu_2831_p4 = {{pX[31:1]}};

assign tmp_data_0_V_1_fu_4573_p2 = ($signed(add_ln703_1890_fu_4565_p2) + $signed(sext_ln703_644_fu_4570_p1));

assign tmp_data_1_V_fu_4590_p2 = ($signed(add_ln703_1898_fu_4582_p2) + $signed(sext_ln703_649_fu_4587_p1));

assign tmp_data_2_V_fu_4607_p2 = ($signed(add_ln703_1905_fu_4599_p2) + $signed(sext_ln703_652_fu_4604_p1));

assign tmp_data_3_V_fu_4625_p2 = (add_ln703_1911_reg_5044 + add_ln703_1915_fu_4619_p2);

assign tmp_data_4_V_fu_4556_p2 = ($signed(add_ln703_1882_fu_4549_p2) + $signed(sext_ln703_639_fu_4553_p1));

assign tmp_data_6_V_fu_4667_p2 = ($signed(add_ln703_1928_fu_4659_p2) + $signed(sext_ln703_668_fu_4664_p1));

assign tmp_data_7_V_fu_4680_p2 = ($signed(add_ln703_1937_fu_4673_p2) + $signed(sext_ln703_672_fu_4677_p1));

assign tmp_fu_2811_p4 = {{pY[31:1]}};

assign trunc_ln708_688_fu_3233_p4 = {{add_ln1118_75_fu_3227_p2[13:1]}};

assign trunc_ln708_689_fu_3253_p4 = {{sub_ln1118_692_fu_3247_p2[13:1]}};

assign trunc_ln708_690_fu_3284_p4 = {{sub_ln1118_693_fu_3278_p2[14:1]}};

assign trunc_ln708_695_fu_3358_p1 = line_buffer_Array_V_1_0_q0;

assign trunc_ln708_695_fu_3358_p4 = {{trunc_ln708_695_fu_3358_p1[10:1]}};

assign trunc_ln708_697_fu_4010_p4 = {{sub_ln1118_569_fu_4004_p2[12:1]}};

assign trunc_ln708_699_fu_4043_p4 = {{sub_ln1118_571_fu_4037_p2[11:1]}};

assign trunc_ln708_700_fu_3416_p4 = {{kernel_data_V_4_load_reg_4753[10:1]}};

assign trunc_ln708_701_fu_4085_p4 = {{sub_ln1118_572_fu_4079_p2[15:1]}};

assign trunc_ln708_702_fu_4116_p4 = {{sub_ln1118_573_fu_4110_p2[13:1]}};

assign trunc_ln708_707_fu_3488_p4 = {{sub_ln1118_575_fu_3482_p2[15:1]}};

assign trunc_ln708_710_fu_4169_p4 = {{sub_ln1118_577_fu_4163_p2[12:1]}};

assign trunc_ln708_712_fu_3572_p4 = {{sub_ln1118_578_fu_3566_p2[12:1]}};

assign trunc_ln708_722_fu_3813_p4 = {{add_ln1118_78_fu_3807_p2[14:1]}};

assign trunc_ln708_723_fu_3845_p4 = {{sub_ln1118_696_fu_3839_p2[13:1]}};

assign trunc_ln708_724_fu_3868_p4 = {{sub_ln1118_586_fu_3862_p2[11:1]}};

assign trunc_ln708_725_fu_4236_p4 = {{sub_ln1118_587_fu_4230_p2[13:1]}};

assign trunc_ln708_726_fu_4267_p4 = {{sub_ln1118_588_fu_4261_p2[12:1]}};

assign trunc_ln708_727_fu_3882_p4 = {{tmp_data_0_V_reg_4725[10:1]}};

assign trunc_ln708_s_fu_3130_p4 = {{add_ln1118_74_fu_3124_p2[13:1]}};

assign trunc_ln_fu_3099_p4 = {{add_ln1118_fu_3093_p2[15:1]}};

always @ (posedge ap_clk) begin
    sext_ln1118_450_reg_4830[2:0] <= 3'b000;
    sext_ln1118_450_reg_4830_pp0_iter3_reg[2:0] <= 3'b000;
end

endmodule //conv_2d_cl_array_ap_fixed_1u_array_ap_fixed_16_6_5_3_0_8u_config3_s
