-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity dense_array_ap_ufixed_8u_array_ap_fixed_16_6_5_3_0_16u_config7_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    data_stream_V_data_0_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_0_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_0_V_read : OUT STD_LOGIC;
    data_stream_V_data_1_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_1_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_1_V_read : OUT STD_LOGIC;
    data_stream_V_data_2_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_2_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_2_V_read : OUT STD_LOGIC;
    data_stream_V_data_3_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_3_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_3_V_read : OUT STD_LOGIC;
    data_stream_V_data_4_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_4_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_4_V_read : OUT STD_LOGIC;
    data_stream_V_data_5_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_5_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_5_V_read : OUT STD_LOGIC;
    data_stream_V_data_6_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_6_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_6_V_read : OUT STD_LOGIC;
    data_stream_V_data_7_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    data_stream_V_data_7_V_empty_n : IN STD_LOGIC;
    data_stream_V_data_7_V_read : OUT STD_LOGIC;
    res_stream_V_data_0_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_0_V_full_n : IN STD_LOGIC;
    res_stream_V_data_0_V_write : OUT STD_LOGIC;
    res_stream_V_data_1_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_1_V_full_n : IN STD_LOGIC;
    res_stream_V_data_1_V_write : OUT STD_LOGIC;
    res_stream_V_data_2_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_2_V_full_n : IN STD_LOGIC;
    res_stream_V_data_2_V_write : OUT STD_LOGIC;
    res_stream_V_data_3_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_3_V_full_n : IN STD_LOGIC;
    res_stream_V_data_3_V_write : OUT STD_LOGIC;
    res_stream_V_data_4_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_4_V_full_n : IN STD_LOGIC;
    res_stream_V_data_4_V_write : OUT STD_LOGIC;
    res_stream_V_data_5_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_5_V_full_n : IN STD_LOGIC;
    res_stream_V_data_5_V_write : OUT STD_LOGIC;
    res_stream_V_data_6_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_6_V_full_n : IN STD_LOGIC;
    res_stream_V_data_6_V_write : OUT STD_LOGIC;
    res_stream_V_data_7_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_7_V_full_n : IN STD_LOGIC;
    res_stream_V_data_7_V_write : OUT STD_LOGIC;
    res_stream_V_data_8_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_8_V_full_n : IN STD_LOGIC;
    res_stream_V_data_8_V_write : OUT STD_LOGIC;
    res_stream_V_data_9_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_9_V_full_n : IN STD_LOGIC;
    res_stream_V_data_9_V_write : OUT STD_LOGIC;
    res_stream_V_data_10_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_10_V_full_n : IN STD_LOGIC;
    res_stream_V_data_10_V_write : OUT STD_LOGIC;
    res_stream_V_data_11_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_11_V_full_n : IN STD_LOGIC;
    res_stream_V_data_11_V_write : OUT STD_LOGIC;
    res_stream_V_data_12_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_12_V_full_n : IN STD_LOGIC;
    res_stream_V_data_12_V_write : OUT STD_LOGIC;
    res_stream_V_data_13_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_13_V_full_n : IN STD_LOGIC;
    res_stream_V_data_13_V_write : OUT STD_LOGIC;
    res_stream_V_data_14_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_14_V_full_n : IN STD_LOGIC;
    res_stream_V_data_14_V_write : OUT STD_LOGIC;
    res_stream_V_data_15_V_din : OUT STD_LOGIC_VECTOR (15 downto 0);
    res_stream_V_data_15_V_full_n : IN STD_LOGIC;
    res_stream_V_data_15_V_write : OUT STD_LOGIC );
end;


architecture behav of dense_array_ap_ufixed_8u_array_ap_fixed_16_6_5_3_0_16u_config7_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal data_stream_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal data_stream_V_data_1_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_2_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_3_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_4_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_5_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_6_V_blk_n : STD_LOGIC;
    signal data_stream_V_data_7_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_0_V_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal res_stream_V_data_1_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_2_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_3_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_4_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_5_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_6_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_7_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_8_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_9_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_10_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_11_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_12_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_13_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_14_V_blk_n : STD_LOGIC;
    signal res_stream_V_data_15_V_blk_n : STD_LOGIC;
    signal i_in_0_reg_996 : STD_LOGIC_VECTOR (4 downto 0);
    signal icmp_ln36_fu_1139_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal io_acc_block_signal_op298 : STD_LOGIC;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal i_in_fu_1145_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal trunc_ln356_fu_1151_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln356_reg_3180 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_data_0_V_reg_3824 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_ready : STD_LOGIC;
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_done : STD_LOGIC;
    signal tmp_data_1_V_reg_3829 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_2_V_reg_3834 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_3_V_reg_3839 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_4_V_reg_3844 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_5_V_reg_3849 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_6_V_reg_3854 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_7_V_reg_3859 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_8_V_reg_3864 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_9_V_reg_3869 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_10_V_reg_3874 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_11_V_reg_3879 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_12_V_reg_3884 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_13_V_reg_3889 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_14_V_reg_3894 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_data_15_V_reg_3899 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start : STD_LOGIC;
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_idle : STD_LOGIC;
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_0 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_1 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_2 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_3 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_4 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_5 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_6 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_7 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_8 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_9 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_10 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_11 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_12 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_13 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_14 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_15 : STD_LOGIC_VECTOR (15 downto 0);
    signal grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start_reg : STD_LOGIC := '0';
    signal data_120_V_fu_412 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_fu_416 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_fu_420 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_fu_424 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_fu_428 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_fu_432 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_fu_436 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_fu_440 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_1_fu_444 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_1_fu_448 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_1_fu_452 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_1_fu_456 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_1_fu_460 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_1_fu_464 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_1_fu_468 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_1_fu_472 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_2_fu_476 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_2_fu_480 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_2_fu_484 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_2_fu_488 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_2_fu_492 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_2_fu_496 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_2_fu_500 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_2_fu_504 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_3_fu_508 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_3_fu_512 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_3_fu_516 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_3_fu_520 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_3_fu_524 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_3_fu_528 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_3_fu_532 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_3_fu_536 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_4_fu_540 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_4_fu_544 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_4_fu_548 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_4_fu_552 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_4_fu_556 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_4_fu_560 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_4_fu_564 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_4_fu_568 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_5_fu_572 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_5_fu_576 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_5_fu_580 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_5_fu_584 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_5_fu_588 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_5_fu_592 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_5_fu_596 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_5_fu_600 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_6_fu_604 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_6_fu_608 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_6_fu_612 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_6_fu_616 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_6_fu_620 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_6_fu_624 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_6_fu_628 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_6_fu_632 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_7_fu_636 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_7_fu_640 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_7_fu_644 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_7_fu_648 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_7_fu_652 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_7_fu_656 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_7_fu_660 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_7_fu_664 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_8_fu_668 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_8_fu_672 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_8_fu_676 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_8_fu_680 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_8_fu_684 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_8_fu_688 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_8_fu_692 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_8_fu_696 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_9_fu_700 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_9_fu_704 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_9_fu_708 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_9_fu_712 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_9_fu_716 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_9_fu_720 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_9_fu_724 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_9_fu_728 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_10_fu_732 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_10_fu_736 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_10_fu_740 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_10_fu_744 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_10_fu_748 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_10_fu_752 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_10_fu_756 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_10_fu_760 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_11_fu_764 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_11_fu_768 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_11_fu_772 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_11_fu_776 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_11_fu_780 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_11_fu_784 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_11_fu_788 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_11_fu_792 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_12_fu_796 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_12_fu_800 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_12_fu_804 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_12_fu_808 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_12_fu_812 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_12_fu_816 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_12_fu_820 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_12_fu_824 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_13_fu_828 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_13_fu_832 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_13_fu_836 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_13_fu_840 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_13_fu_844 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_13_fu_848 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_13_fu_852 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_13_fu_856 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_14_fu_860 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_14_fu_864 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_14_fu_868 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_14_fu_872 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_14_fu_876 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_14_fu_880 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_14_fu_884 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_14_fu_888 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_120_V_15_fu_892 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_121_V_15_fu_896 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_122_V_15_fu_900 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_123_V_15_fu_904 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_124_V_15_fu_908 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_125_V_15_fu_912 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_126_V_15_fu_916 : STD_LOGIC_VECTOR (11 downto 0);
    signal data_127_V_15_fu_920 : STD_LOGIC_VECTOR (11 downto 0);
    signal io_acc_block_signal_op591 : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;

    component dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        data_0_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_1_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_2_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_3_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_4_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_5_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_6_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_7_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_8_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_9_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_10_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_11_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_12_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_13_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_14_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_15_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_16_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_17_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_18_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_19_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_20_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_21_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_22_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_23_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_24_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_25_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_26_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_27_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_28_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_29_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_30_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_31_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_32_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_33_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_34_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_35_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_36_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_37_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_38_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_39_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_40_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_41_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_42_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_43_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_44_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_45_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_46_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_47_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_48_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_49_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_50_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_51_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_52_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_53_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_54_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_55_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_56_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_57_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_58_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_59_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_60_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_61_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_62_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_63_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_64_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_65_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_66_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_67_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_68_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_69_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_70_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_71_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_72_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_73_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_74_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_75_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_76_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_77_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_78_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_79_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_80_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_81_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_82_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_83_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_84_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_85_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_86_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_87_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_88_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_89_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_90_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_91_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_92_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_93_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_94_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_95_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_96_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_97_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_98_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_99_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_100_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_101_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_102_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_103_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_104_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_105_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_106_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_107_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_108_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_109_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_110_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_111_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_112_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_113_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_114_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_115_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_116_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_117_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_118_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_119_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_120_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_121_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_122_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_123_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_124_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_125_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_126_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        data_127_V_read : IN STD_LOGIC_VECTOR (11 downto 0);
        ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_7 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_8 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_9 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_10 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_11 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_12 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_13 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_14 : OUT STD_LOGIC_VECTOR (15 downto 0);
        ap_return_15 : OUT STD_LOGIC_VECTOR (15 downto 0) );
    end component;



begin
    grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007 : component dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start,
        ap_done => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_done,
        ap_idle => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_idle,
        ap_ready => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_ready,
        data_0_V_read => data_120_V_fu_412,
        data_1_V_read => data_121_V_fu_416,
        data_2_V_read => data_122_V_fu_420,
        data_3_V_read => data_123_V_fu_424,
        data_4_V_read => data_124_V_fu_428,
        data_5_V_read => data_125_V_fu_432,
        data_6_V_read => data_126_V_fu_436,
        data_7_V_read => data_127_V_fu_440,
        data_8_V_read => data_120_V_1_fu_444,
        data_9_V_read => data_121_V_1_fu_448,
        data_10_V_read => data_122_V_1_fu_452,
        data_11_V_read => data_123_V_1_fu_456,
        data_12_V_read => data_124_V_1_fu_460,
        data_13_V_read => data_125_V_1_fu_464,
        data_14_V_read => data_126_V_1_fu_468,
        data_15_V_read => data_127_V_1_fu_472,
        data_16_V_read => data_120_V_2_fu_476,
        data_17_V_read => data_121_V_2_fu_480,
        data_18_V_read => data_122_V_2_fu_484,
        data_19_V_read => data_123_V_2_fu_488,
        data_20_V_read => data_124_V_2_fu_492,
        data_21_V_read => data_125_V_2_fu_496,
        data_22_V_read => data_126_V_2_fu_500,
        data_23_V_read => data_127_V_2_fu_504,
        data_24_V_read => data_120_V_3_fu_508,
        data_25_V_read => data_121_V_3_fu_512,
        data_26_V_read => data_122_V_3_fu_516,
        data_27_V_read => data_123_V_3_fu_520,
        data_28_V_read => data_124_V_3_fu_524,
        data_29_V_read => data_125_V_3_fu_528,
        data_30_V_read => data_126_V_3_fu_532,
        data_31_V_read => data_127_V_3_fu_536,
        data_32_V_read => data_120_V_4_fu_540,
        data_33_V_read => data_121_V_4_fu_544,
        data_34_V_read => data_122_V_4_fu_548,
        data_35_V_read => data_123_V_4_fu_552,
        data_36_V_read => data_124_V_4_fu_556,
        data_37_V_read => data_125_V_4_fu_560,
        data_38_V_read => data_126_V_4_fu_564,
        data_39_V_read => data_127_V_4_fu_568,
        data_40_V_read => data_120_V_5_fu_572,
        data_41_V_read => data_121_V_5_fu_576,
        data_42_V_read => data_122_V_5_fu_580,
        data_43_V_read => data_123_V_5_fu_584,
        data_44_V_read => data_124_V_5_fu_588,
        data_45_V_read => data_125_V_5_fu_592,
        data_46_V_read => data_126_V_5_fu_596,
        data_47_V_read => data_127_V_5_fu_600,
        data_48_V_read => data_120_V_6_fu_604,
        data_49_V_read => data_121_V_6_fu_608,
        data_50_V_read => data_122_V_6_fu_612,
        data_51_V_read => data_123_V_6_fu_616,
        data_52_V_read => data_124_V_6_fu_620,
        data_53_V_read => data_125_V_6_fu_624,
        data_54_V_read => data_126_V_6_fu_628,
        data_55_V_read => data_127_V_6_fu_632,
        data_56_V_read => data_120_V_7_fu_636,
        data_57_V_read => data_121_V_7_fu_640,
        data_58_V_read => data_122_V_7_fu_644,
        data_59_V_read => data_123_V_7_fu_648,
        data_60_V_read => data_124_V_7_fu_652,
        data_61_V_read => data_125_V_7_fu_656,
        data_62_V_read => data_126_V_7_fu_660,
        data_63_V_read => data_127_V_7_fu_664,
        data_64_V_read => data_120_V_8_fu_668,
        data_65_V_read => data_121_V_8_fu_672,
        data_66_V_read => data_122_V_8_fu_676,
        data_67_V_read => data_123_V_8_fu_680,
        data_68_V_read => data_124_V_8_fu_684,
        data_69_V_read => data_125_V_8_fu_688,
        data_70_V_read => data_126_V_8_fu_692,
        data_71_V_read => data_127_V_8_fu_696,
        data_72_V_read => data_120_V_9_fu_700,
        data_73_V_read => data_121_V_9_fu_704,
        data_74_V_read => data_122_V_9_fu_708,
        data_75_V_read => data_123_V_9_fu_712,
        data_76_V_read => data_124_V_9_fu_716,
        data_77_V_read => data_125_V_9_fu_720,
        data_78_V_read => data_126_V_9_fu_724,
        data_79_V_read => data_127_V_9_fu_728,
        data_80_V_read => data_120_V_10_fu_732,
        data_81_V_read => data_121_V_10_fu_736,
        data_82_V_read => data_122_V_10_fu_740,
        data_83_V_read => data_123_V_10_fu_744,
        data_84_V_read => data_124_V_10_fu_748,
        data_85_V_read => data_125_V_10_fu_752,
        data_86_V_read => data_126_V_10_fu_756,
        data_87_V_read => data_127_V_10_fu_760,
        data_88_V_read => data_120_V_11_fu_764,
        data_89_V_read => data_121_V_11_fu_768,
        data_90_V_read => data_122_V_11_fu_772,
        data_91_V_read => data_123_V_11_fu_776,
        data_92_V_read => data_124_V_11_fu_780,
        data_93_V_read => data_125_V_11_fu_784,
        data_94_V_read => data_126_V_11_fu_788,
        data_95_V_read => data_127_V_11_fu_792,
        data_96_V_read => data_120_V_12_fu_796,
        data_97_V_read => data_121_V_12_fu_800,
        data_98_V_read => data_122_V_12_fu_804,
        data_99_V_read => data_123_V_12_fu_808,
        data_100_V_read => data_124_V_12_fu_812,
        data_101_V_read => data_125_V_12_fu_816,
        data_102_V_read => data_126_V_12_fu_820,
        data_103_V_read => data_127_V_12_fu_824,
        data_104_V_read => data_120_V_13_fu_828,
        data_105_V_read => data_121_V_13_fu_832,
        data_106_V_read => data_122_V_13_fu_836,
        data_107_V_read => data_123_V_13_fu_840,
        data_108_V_read => data_124_V_13_fu_844,
        data_109_V_read => data_125_V_13_fu_848,
        data_110_V_read => data_126_V_13_fu_852,
        data_111_V_read => data_127_V_13_fu_856,
        data_112_V_read => data_120_V_14_fu_860,
        data_113_V_read => data_121_V_14_fu_864,
        data_114_V_read => data_122_V_14_fu_868,
        data_115_V_read => data_123_V_14_fu_872,
        data_116_V_read => data_124_V_14_fu_876,
        data_117_V_read => data_125_V_14_fu_880,
        data_118_V_read => data_126_V_14_fu_884,
        data_119_V_read => data_127_V_14_fu_888,
        data_120_V_read => data_120_V_15_fu_892,
        data_121_V_read => data_121_V_15_fu_896,
        data_122_V_read => data_122_V_15_fu_900,
        data_123_V_read => data_123_V_15_fu_904,
        data_124_V_read => data_124_V_15_fu_908,
        data_125_V_read => data_125_V_15_fu_912,
        data_126_V_read => data_126_V_15_fu_916,
        data_127_V_read => data_127_V_15_fu_920,
        ap_return_0 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_0,
        ap_return_1 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_1,
        ap_return_2 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_2,
        ap_return_3 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_3,
        ap_return_4 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_4,
        ap_return_5 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_5,
        ap_return_6 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_6,
        ap_return_7 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_7,
        ap_return_8 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_8,
        ap_return_9 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_9,
        ap_return_10 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_10,
        ap_return_11 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_11,
        ap_return_12 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_12,
        ap_return_13 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_13,
        ap_return_14 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_14,
        ap_return_15 => grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_15);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2))) then 
                    ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                elsif ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                    grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_ready = ap_const_logic_1)) then 
                    grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    i_in_0_reg_996_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln36_fu_1139_p2 = ap_const_lv1_0))) then 
                i_in_0_reg_996 <= i_in_fu_1145_p2;
            elsif ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                i_in_0_reg_996 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_A) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_10_fu_732 <= data_stream_V_data_0_V_dout;
                data_121_V_10_fu_736 <= data_stream_V_data_1_V_dout;
                data_122_V_10_fu_740 <= data_stream_V_data_2_V_dout;
                data_123_V_10_fu_744 <= data_stream_V_data_3_V_dout;
                data_124_V_10_fu_748 <= data_stream_V_data_4_V_dout;
                data_125_V_10_fu_752 <= data_stream_V_data_5_V_dout;
                data_126_V_10_fu_756 <= data_stream_V_data_6_V_dout;
                data_127_V_10_fu_760 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_B) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_11_fu_764 <= data_stream_V_data_0_V_dout;
                data_121_V_11_fu_768 <= data_stream_V_data_1_V_dout;
                data_122_V_11_fu_772 <= data_stream_V_data_2_V_dout;
                data_123_V_11_fu_776 <= data_stream_V_data_3_V_dout;
                data_124_V_11_fu_780 <= data_stream_V_data_4_V_dout;
                data_125_V_11_fu_784 <= data_stream_V_data_5_V_dout;
                data_126_V_11_fu_788 <= data_stream_V_data_6_V_dout;
                data_127_V_11_fu_792 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_C) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_12_fu_796 <= data_stream_V_data_0_V_dout;
                data_121_V_12_fu_800 <= data_stream_V_data_1_V_dout;
                data_122_V_12_fu_804 <= data_stream_V_data_2_V_dout;
                data_123_V_12_fu_808 <= data_stream_V_data_3_V_dout;
                data_124_V_12_fu_812 <= data_stream_V_data_4_V_dout;
                data_125_V_12_fu_816 <= data_stream_V_data_5_V_dout;
                data_126_V_12_fu_820 <= data_stream_V_data_6_V_dout;
                data_127_V_12_fu_824 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_D) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_13_fu_828 <= data_stream_V_data_0_V_dout;
                data_121_V_13_fu_832 <= data_stream_V_data_1_V_dout;
                data_122_V_13_fu_836 <= data_stream_V_data_2_V_dout;
                data_123_V_13_fu_840 <= data_stream_V_data_3_V_dout;
                data_124_V_13_fu_844 <= data_stream_V_data_4_V_dout;
                data_125_V_13_fu_848 <= data_stream_V_data_5_V_dout;
                data_126_V_13_fu_852 <= data_stream_V_data_6_V_dout;
                data_127_V_13_fu_856 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_E) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_14_fu_860 <= data_stream_V_data_0_V_dout;
                data_121_V_14_fu_864 <= data_stream_V_data_1_V_dout;
                data_122_V_14_fu_868 <= data_stream_V_data_2_V_dout;
                data_123_V_14_fu_872 <= data_stream_V_data_3_V_dout;
                data_124_V_14_fu_876 <= data_stream_V_data_4_V_dout;
                data_125_V_14_fu_880 <= data_stream_V_data_5_V_dout;
                data_126_V_14_fu_884 <= data_stream_V_data_6_V_dout;
                data_127_V_14_fu_888 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_F) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_15_fu_892 <= data_stream_V_data_0_V_dout;
                data_121_V_15_fu_896 <= data_stream_V_data_1_V_dout;
                data_122_V_15_fu_900 <= data_stream_V_data_2_V_dout;
                data_123_V_15_fu_904 <= data_stream_V_data_3_V_dout;
                data_124_V_15_fu_908 <= data_stream_V_data_4_V_dout;
                data_125_V_15_fu_912 <= data_stream_V_data_5_V_dout;
                data_126_V_15_fu_916 <= data_stream_V_data_6_V_dout;
                data_127_V_15_fu_920 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_1_fu_444 <= data_stream_V_data_0_V_dout;
                data_121_V_1_fu_448 <= data_stream_V_data_1_V_dout;
                data_122_V_1_fu_452 <= data_stream_V_data_2_V_dout;
                data_123_V_1_fu_456 <= data_stream_V_data_3_V_dout;
                data_124_V_1_fu_460 <= data_stream_V_data_4_V_dout;
                data_125_V_1_fu_464 <= data_stream_V_data_5_V_dout;
                data_126_V_1_fu_468 <= data_stream_V_data_6_V_dout;
                data_127_V_1_fu_472 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_2_fu_476 <= data_stream_V_data_0_V_dout;
                data_121_V_2_fu_480 <= data_stream_V_data_1_V_dout;
                data_122_V_2_fu_484 <= data_stream_V_data_2_V_dout;
                data_123_V_2_fu_488 <= data_stream_V_data_3_V_dout;
                data_124_V_2_fu_492 <= data_stream_V_data_4_V_dout;
                data_125_V_2_fu_496 <= data_stream_V_data_5_V_dout;
                data_126_V_2_fu_500 <= data_stream_V_data_6_V_dout;
                data_127_V_2_fu_504 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_3_fu_508 <= data_stream_V_data_0_V_dout;
                data_121_V_3_fu_512 <= data_stream_V_data_1_V_dout;
                data_122_V_3_fu_516 <= data_stream_V_data_2_V_dout;
                data_123_V_3_fu_520 <= data_stream_V_data_3_V_dout;
                data_124_V_3_fu_524 <= data_stream_V_data_4_V_dout;
                data_125_V_3_fu_528 <= data_stream_V_data_5_V_dout;
                data_126_V_3_fu_532 <= data_stream_V_data_6_V_dout;
                data_127_V_3_fu_536 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_4_fu_540 <= data_stream_V_data_0_V_dout;
                data_121_V_4_fu_544 <= data_stream_V_data_1_V_dout;
                data_122_V_4_fu_548 <= data_stream_V_data_2_V_dout;
                data_123_V_4_fu_552 <= data_stream_V_data_3_V_dout;
                data_124_V_4_fu_556 <= data_stream_V_data_4_V_dout;
                data_125_V_4_fu_560 <= data_stream_V_data_5_V_dout;
                data_126_V_4_fu_564 <= data_stream_V_data_6_V_dout;
                data_127_V_4_fu_568 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_5_fu_572 <= data_stream_V_data_0_V_dout;
                data_121_V_5_fu_576 <= data_stream_V_data_1_V_dout;
                data_122_V_5_fu_580 <= data_stream_V_data_2_V_dout;
                data_123_V_5_fu_584 <= data_stream_V_data_3_V_dout;
                data_124_V_5_fu_588 <= data_stream_V_data_4_V_dout;
                data_125_V_5_fu_592 <= data_stream_V_data_5_V_dout;
                data_126_V_5_fu_596 <= data_stream_V_data_6_V_dout;
                data_127_V_5_fu_600 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_6_fu_604 <= data_stream_V_data_0_V_dout;
                data_121_V_6_fu_608 <= data_stream_V_data_1_V_dout;
                data_122_V_6_fu_612 <= data_stream_V_data_2_V_dout;
                data_123_V_6_fu_616 <= data_stream_V_data_3_V_dout;
                data_124_V_6_fu_620 <= data_stream_V_data_4_V_dout;
                data_125_V_6_fu_624 <= data_stream_V_data_5_V_dout;
                data_126_V_6_fu_628 <= data_stream_V_data_6_V_dout;
                data_127_V_6_fu_632 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_7_fu_636 <= data_stream_V_data_0_V_dout;
                data_121_V_7_fu_640 <= data_stream_V_data_1_V_dout;
                data_122_V_7_fu_644 <= data_stream_V_data_2_V_dout;
                data_123_V_7_fu_648 <= data_stream_V_data_3_V_dout;
                data_124_V_7_fu_652 <= data_stream_V_data_4_V_dout;
                data_125_V_7_fu_656 <= data_stream_V_data_5_V_dout;
                data_126_V_7_fu_660 <= data_stream_V_data_6_V_dout;
                data_127_V_7_fu_664 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_8) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_8_fu_668 <= data_stream_V_data_0_V_dout;
                data_121_V_8_fu_672 <= data_stream_V_data_1_V_dout;
                data_122_V_8_fu_676 <= data_stream_V_data_2_V_dout;
                data_123_V_8_fu_680 <= data_stream_V_data_3_V_dout;
                data_124_V_8_fu_684 <= data_stream_V_data_4_V_dout;
                data_125_V_8_fu_688 <= data_stream_V_data_5_V_dout;
                data_126_V_8_fu_692 <= data_stream_V_data_6_V_dout;
                data_127_V_8_fu_696 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_9) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_9_fu_700 <= data_stream_V_data_0_V_dout;
                data_121_V_9_fu_704 <= data_stream_V_data_1_V_dout;
                data_122_V_9_fu_708 <= data_stream_V_data_2_V_dout;
                data_123_V_9_fu_712 <= data_stream_V_data_3_V_dout;
                data_124_V_9_fu_716 <= data_stream_V_data_4_V_dout;
                data_125_V_9_fu_720 <= data_stream_V_data_5_V_dout;
                data_126_V_9_fu_724 <= data_stream_V_data_6_V_dout;
                data_127_V_9_fu_728 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((trunc_ln356_reg_3180 = ap_const_lv4_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                data_120_V_fu_412 <= data_stream_V_data_0_V_dout;
                data_121_V_fu_416 <= data_stream_V_data_1_V_dout;
                data_122_V_fu_420 <= data_stream_V_data_2_V_dout;
                data_123_V_fu_424 <= data_stream_V_data_3_V_dout;
                data_124_V_fu_428 <= data_stream_V_data_4_V_dout;
                data_125_V_fu_432 <= data_stream_V_data_5_V_dout;
                data_126_V_fu_436 <= data_stream_V_data_6_V_dout;
                data_127_V_fu_440 <= data_stream_V_data_7_V_dout;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                tmp_data_0_V_reg_3824 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_0;
                tmp_data_10_V_reg_3874 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_10;
                tmp_data_11_V_reg_3879 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_11;
                tmp_data_12_V_reg_3884 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_12;
                tmp_data_13_V_reg_3889 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_13;
                tmp_data_14_V_reg_3894 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_14;
                tmp_data_15_V_reg_3899 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_15;
                tmp_data_1_V_reg_3829 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_1;
                tmp_data_2_V_reg_3834 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_2;
                tmp_data_3_V_reg_3839 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_3;
                tmp_data_4_V_reg_3844 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_4;
                tmp_data_5_V_reg_3849 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_5;
                tmp_data_6_V_reg_3854 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_6;
                tmp_data_7_V_reg_3859 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_7;
                tmp_data_8_V_reg_3864 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_8;
                tmp_data_9_V_reg_3869 <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_return_9;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (icmp_ln36_fu_1139_p2 = ap_const_lv1_0))) then
                trunc_ln356_reg_3180 <= trunc_ln356_fu_1151_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state6, icmp_ln36_fu_1139_p2, ap_enable_reg_pp0_iter0, ap_CS_fsm_state5, grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_done, ap_block_pp0_stage0_subdone, io_acc_block_signal_op591)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln36_fu_1139_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (icmp_ln36_fu_1139_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                if (((grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state4 <= ap_CS_fsm(2);
    ap_CS_fsm_state5 <= ap_CS_fsm(3);
    ap_CS_fsm_state6 <= ap_CS_fsm(4);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, io_acc_block_signal_op298)
    begin
                ap_block_pp0_stage0_11001 <= ((io_acc_block_signal_op298 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, io_acc_block_signal_op298)
    begin
                ap_block_pp0_stage0_subdone <= ((io_acc_block_signal_op298 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg)
    begin
                ap_block_state1 <= ((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;

        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state3_pp0_stage0_iter1_assign_proc : process(io_acc_block_signal_op298)
    begin
                ap_block_state3_pp0_stage0_iter1 <= (io_acc_block_signal_op298 = ap_const_logic_0);
    end process;


    ap_condition_pp0_exit_iter0_state2_assign_proc : process(icmp_ln36_fu_1139_p2)
    begin
        if ((icmp_ln36_fu_1139_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter0)
    begin
        if (((ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_ready <= internal_ap_ready;

    data_stream_V_data_0_V_blk_n_assign_proc : process(data_stream_V_data_0_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_0_V_blk_n <= data_stream_V_data_0_V_empty_n;
        else 
            data_stream_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_0_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_0_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_0_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_1_V_blk_n_assign_proc : process(data_stream_V_data_1_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_1_V_blk_n <= data_stream_V_data_1_V_empty_n;
        else 
            data_stream_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_1_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_1_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_1_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_2_V_blk_n_assign_proc : process(data_stream_V_data_2_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_2_V_blk_n <= data_stream_V_data_2_V_empty_n;
        else 
            data_stream_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_2_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_2_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_2_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_3_V_blk_n_assign_proc : process(data_stream_V_data_3_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_3_V_blk_n <= data_stream_V_data_3_V_empty_n;
        else 
            data_stream_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_3_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_3_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_3_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_4_V_blk_n_assign_proc : process(data_stream_V_data_4_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_4_V_blk_n <= data_stream_V_data_4_V_empty_n;
        else 
            data_stream_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_4_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_4_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_4_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_5_V_blk_n_assign_proc : process(data_stream_V_data_5_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_5_V_blk_n <= data_stream_V_data_5_V_empty_n;
        else 
            data_stream_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_5_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_5_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_5_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_6_V_blk_n_assign_proc : process(data_stream_V_data_6_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_6_V_blk_n <= data_stream_V_data_6_V_empty_n;
        else 
            data_stream_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_6_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_6_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_6_V_read <= ap_const_logic_0;
        end if; 
    end process;


    data_stream_V_data_7_V_blk_n_assign_proc : process(data_stream_V_data_7_V_empty_n, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0))) then 
            data_stream_V_data_7_V_blk_n <= data_stream_V_data_7_V_empty_n;
        else 
            data_stream_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    data_stream_V_data_7_V_read_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            data_stream_V_data_7_V_read <= ap_const_logic_1;
        else 
            data_stream_V_data_7_V_read <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start <= grp_dense_wrapper_ap_ufixed_12_3_4_0_0_ap_fixed_16_6_5_3_0_config7_s_fu_1007_ap_start_reg;
    i_in_fu_1145_p2 <= std_logic_vector(unsigned(i_in_0_reg_996) + unsigned(ap_const_lv5_1));
    icmp_ln36_fu_1139_p2 <= "1" when (i_in_0_reg_996 = ap_const_lv5_10) else "0";

    internal_ap_ready_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    io_acc_block_signal_op298 <= (data_stream_V_data_7_V_empty_n and data_stream_V_data_6_V_empty_n and data_stream_V_data_5_V_empty_n and data_stream_V_data_4_V_empty_n and data_stream_V_data_3_V_empty_n and data_stream_V_data_2_V_empty_n and data_stream_V_data_1_V_empty_n and data_stream_V_data_0_V_empty_n);
    io_acc_block_signal_op591 <= (res_stream_V_data_9_V_full_n and res_stream_V_data_8_V_full_n and res_stream_V_data_7_V_full_n and res_stream_V_data_6_V_full_n and res_stream_V_data_5_V_full_n and res_stream_V_data_4_V_full_n and res_stream_V_data_3_V_full_n and res_stream_V_data_2_V_full_n and res_stream_V_data_1_V_full_n and res_stream_V_data_15_V_full_n and res_stream_V_data_14_V_full_n and res_stream_V_data_13_V_full_n and res_stream_V_data_12_V_full_n and res_stream_V_data_11_V_full_n and res_stream_V_data_10_V_full_n and res_stream_V_data_0_V_full_n);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;


    res_stream_V_data_0_V_blk_n_assign_proc : process(res_stream_V_data_0_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_0_V_blk_n <= res_stream_V_data_0_V_full_n;
        else 
            res_stream_V_data_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_0_V_din <= tmp_data_0_V_reg_3824;

    res_stream_V_data_0_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_0_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_10_V_blk_n_assign_proc : process(res_stream_V_data_10_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_10_V_blk_n <= res_stream_V_data_10_V_full_n;
        else 
            res_stream_V_data_10_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_10_V_din <= tmp_data_10_V_reg_3874;

    res_stream_V_data_10_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_10_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_10_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_11_V_blk_n_assign_proc : process(res_stream_V_data_11_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_11_V_blk_n <= res_stream_V_data_11_V_full_n;
        else 
            res_stream_V_data_11_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_11_V_din <= tmp_data_11_V_reg_3879;

    res_stream_V_data_11_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_11_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_11_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_12_V_blk_n_assign_proc : process(res_stream_V_data_12_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_12_V_blk_n <= res_stream_V_data_12_V_full_n;
        else 
            res_stream_V_data_12_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_12_V_din <= tmp_data_12_V_reg_3884;

    res_stream_V_data_12_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_12_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_12_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_13_V_blk_n_assign_proc : process(res_stream_V_data_13_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_13_V_blk_n <= res_stream_V_data_13_V_full_n;
        else 
            res_stream_V_data_13_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_13_V_din <= tmp_data_13_V_reg_3889;

    res_stream_V_data_13_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_13_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_13_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_14_V_blk_n_assign_proc : process(res_stream_V_data_14_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_14_V_blk_n <= res_stream_V_data_14_V_full_n;
        else 
            res_stream_V_data_14_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_14_V_din <= tmp_data_14_V_reg_3894;

    res_stream_V_data_14_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_14_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_14_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_15_V_blk_n_assign_proc : process(res_stream_V_data_15_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_15_V_blk_n <= res_stream_V_data_15_V_full_n;
        else 
            res_stream_V_data_15_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_15_V_din <= tmp_data_15_V_reg_3899;

    res_stream_V_data_15_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_15_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_15_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_1_V_blk_n_assign_proc : process(res_stream_V_data_1_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_1_V_blk_n <= res_stream_V_data_1_V_full_n;
        else 
            res_stream_V_data_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_1_V_din <= tmp_data_1_V_reg_3829;

    res_stream_V_data_1_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_1_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_2_V_blk_n_assign_proc : process(res_stream_V_data_2_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_2_V_blk_n <= res_stream_V_data_2_V_full_n;
        else 
            res_stream_V_data_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_2_V_din <= tmp_data_2_V_reg_3834;

    res_stream_V_data_2_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_2_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_3_V_blk_n_assign_proc : process(res_stream_V_data_3_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_3_V_blk_n <= res_stream_V_data_3_V_full_n;
        else 
            res_stream_V_data_3_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_3_V_din <= tmp_data_3_V_reg_3839;

    res_stream_V_data_3_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_3_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_3_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_4_V_blk_n_assign_proc : process(res_stream_V_data_4_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_4_V_blk_n <= res_stream_V_data_4_V_full_n;
        else 
            res_stream_V_data_4_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_4_V_din <= tmp_data_4_V_reg_3844;

    res_stream_V_data_4_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_4_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_4_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_5_V_blk_n_assign_proc : process(res_stream_V_data_5_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_5_V_blk_n <= res_stream_V_data_5_V_full_n;
        else 
            res_stream_V_data_5_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_5_V_din <= tmp_data_5_V_reg_3849;

    res_stream_V_data_5_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_5_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_5_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_6_V_blk_n_assign_proc : process(res_stream_V_data_6_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_6_V_blk_n <= res_stream_V_data_6_V_full_n;
        else 
            res_stream_V_data_6_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_6_V_din <= tmp_data_6_V_reg_3854;

    res_stream_V_data_6_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_6_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_6_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_7_V_blk_n_assign_proc : process(res_stream_V_data_7_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_7_V_blk_n <= res_stream_V_data_7_V_full_n;
        else 
            res_stream_V_data_7_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_7_V_din <= tmp_data_7_V_reg_3859;

    res_stream_V_data_7_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_7_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_7_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_8_V_blk_n_assign_proc : process(res_stream_V_data_8_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_8_V_blk_n <= res_stream_V_data_8_V_full_n;
        else 
            res_stream_V_data_8_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_8_V_din <= tmp_data_8_V_reg_3864;

    res_stream_V_data_8_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_8_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_8_V_write <= ap_const_logic_0;
        end if; 
    end process;


    res_stream_V_data_9_V_blk_n_assign_proc : process(res_stream_V_data_9_V_full_n, ap_CS_fsm_state6)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            res_stream_V_data_9_V_blk_n <= res_stream_V_data_9_V_full_n;
        else 
            res_stream_V_data_9_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    res_stream_V_data_9_V_din <= tmp_data_9_V_reg_3869;

    res_stream_V_data_9_V_write_assign_proc : process(ap_CS_fsm_state6, io_acc_block_signal_op591)
    begin
        if (((io_acc_block_signal_op591 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
            res_stream_V_data_9_V_write <= ap_const_logic_1;
        else 
            res_stream_V_data_9_V_write <= ap_const_logic_0;
        end if; 
    end process;

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln356_fu_1151_p1 <= i_in_0_reg_996(4 - 1 downto 0);
end behav;
